### ISSUE TITLE
Mobs have no AI. And won't move.

### ISSUE THREAD

**Issue by Pineappleguy03** [AbdElAziz333/Canary#10]
Any Mob from vanilla has no AI. Won't Move and just stands there.

**Comment by Pineappleguy03** [comment]
Spiders... Are Ok Oddly Enough.

**Comment by VeggeieDude** [comment]
I also got this issue. Zombies and Creeper,s don't move at all, but skeletons do

**Comment by HavocJupiter** [comment]
No AI working for villagers, Endermen, Zombies, and Creepers. Possibly more. Skeletons and Spiders work.

**Comment by HavocJupiter** [comment]
I have been able to bandaid-rectify the AI issue by disabling the following optimizations in the config.

mixin.ai.goal=false
mixin.ai.nearby_entity_tracking=false
mixin.ai.pathing=false

These seemed the most logical related to the issue at hand, AI now appears to work.

**Comment by VeggeieDude** [comment]
> I have been able to bandaid-rectify the AI issue by disabling the following optimizations in the config.
> 
> mixin.ai.goal=false mixin.ai.nearby_entity_tracking=false mixin.ai.pathing=false
> 
> These seemed the most logical related to the issue at hand, AI now appears to work.

How did you do this?

**Comment by HavocJupiter** [comment]
> > I have been able to bandaid-rectify the AI issue by disabling the following optimizations in the config.
> > mixin.ai.goal=false mixin.ai.nearby_entity_tracking=false mixin.ai.pathing=false
> > These seemed the most logical related to the issue at hand, AI now appears to work.
> 
> How did you do this?

In your configs folder, you can bring up the config file for Canary. (canary.properties)

By default it is blank aside from some notes. You can add config booleans according to the guide [here](https://github.com/AbdElAziz333/Canary/wiki/Configuration-File). I generally looked at what each setting related to and disabled those three accordingly. Simply add each one of those changed values with their own line in the config file and save.

**Comment by AbdElAziz333** [comment]
Fixed in 0.0.5 update.
