### ISSUE TITLE
The world stops rendering, but time flows normally

### ISSUE THREAD

**Issue by FanRenLa** [AbdElAziz333/Canary#101]
![QQ截图20230203105501](https://user-images.githubusercontent.com/83486178/216501720-14312afe-6512-4951-8927-768c53d8a946.png)
(I don't know English, I don't know how to translate.)
The world stops rendering, but time flows normally
Creatures are stationary, unable to attack or interact
Blocks can be destroyed, but drops cannot be generated

It's FanRenL again, I think I've reported it many times.
canary-mc1.19.2-0.1.8

**Comment by FanRenLa** [comment]
[logs.zip](https://github.com/AbdElAziz333/Canary/files/10575190/logs.zip)
I've been in this situation myself, including other people.
My modpacak will stop using Canary.

**Comment by FanRenLa** [comment]
> [日志.zip](https://github.com/AbdElAziz333/Canary/files/10575190/logs.zip)我自己也遇到过这种情况，包括其他人。我的modpacak将停止使用金丝雀。

Sorry I can't use this mod anymore, can't test it anymore.

**Comment by FanRenLa** [comment]
[modpack.zip](https://github.com/AbdElAziz333/Canary/files/10575220/modpack.zip)
You may not be able to test it alone.

**Comment by electrified0** [comment]
I've also been having this exact issue, so thanks a lot for reporting it. Does the world also get stuck on the "Saving World" screen after pressing Save and Quit? If so, then the problem is called a server-side deadlock for future reference.

**Comment by FanRenLa** [comment]
> 我也遇到了这个确切的问题，所以非常感谢您报告它。按下“保存并退出”后，世界是否也会卡在“拯救世界”屏幕上？如果是这样，则该问题称为服务器端死锁，以供将来参考。

There are even people whose games are not saved and are back to the way they were a few days ago.

**Comment by FanRenLa** [comment]
I'm afraid to use canary anymore.

**Comment by Castafers** [comment]
I'm having the same issue on 1.19.2 on the latest version of Forge.
Spark reports a spike in a tick, however it doesn't show what tick.
Furthermore, Spark reports 20TPS regardless of rendering freezing with any entities/tiles.

This is not an issue with world generation, it is an issue with world rendering.
Sometimes causing random entities/tiles to stop ticking, sometimes they continue to tick.

**Comment by AbdElAziz333** [comment]
can you please use the new update?
[1.19.4](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4498538) - [1.19.3](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4498537) - [1.19.2](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4498536) - [1.18.2](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4498539)
