### ISSUE TITLE
1.19.3 New World Generation Instant Crash

### ISSUE THREAD

**Issue by Zelioth** [AbdElAziz333/Canary#102]
#### Instructions
------------------------

### Version Information

Canary-mc1.19.3-0.1.8
Forge - 44.1.16

### Expected Behavior

World to generate and not crash on startup

### Actual Behavior
As soon as the world renders into view the client will freeze and crash 

### Reproduction Steps

The logs state missing context within the code, but I assume it is some sort of compat issue

### Other Information

](https://gist.github.com/Zelioth/213768df3f72445b92f9099cdc2fb5b9)

**Comment by AbdElAziz333** [comment]
https://github.com/AbdElAziz333/Canary/issues/102
