### ISSUE TITLE
Server before canary has avg tick of 20000ms, after canary it stays between 140000ms and 200000ms

### ISSUE THREAD

**Issue by Askes1s** [AbdElAziz333/Canary#106]
------------------------

### Version Information

> canary-mc1.18.2-0.1.4

### Expected Behavior

> I expected an improvement of the avg ticks on my server but the opposite happened

### Actual Behavior

> The avg ticks are x7 higher at least

### Reproduction Steps

> 1.Put the mod inside the mods folder of my server
> 2. Open the server
> 3. Joining the server (this is the specific moment when the avg ticks go up)

### Other Information

>Mod List:
>![Mod List Pt. 1](https://user-images.githubusercontent.com/125617084/220749857-d5dea7b8-9a62-43fc-863f-a46688c7eb83.png)
>![Mod List Pt. 2](https://user-images.githubusercontent.com/125617084/220750005-2788c164-7a6f-48a9-a63c-a8ce7f03aa85.png)
>![Mod List Pt. 3](https://user-images.githubusercontent.com/125617084/220750185-e5088111-112c-472b-99aa-71112c30afa8.png)
>![Mod List Pt. 4](https://user-images.githubusercontent.com/125617084/220750278-09b4bfb4-70da-41a9-91c8-7aadf780624b.png)
>![Mod List Pt. 5](https://user-images.githubusercontent.com/125617084/220750403-23ccf021-1a4b-49e2-bb1b-9898ab616fac.png)
>Empty Server with Canary:
>![image](https://user-images.githubusercontent.com/125617084/220751400-6ac1d09c-0b80-460d-9fbf-946c345f473f.png)
>Server with 1 player and Canary:
>![image](https://user-images.githubusercontent.com/125617084/220751774-6cd576ad-b90e-4d26-baa8-cfdaee86a050.png)
>Empty Server without Canary:
>![image](https://user-images.githubusercontent.com/125617084/220752389-7d2be769-5db7-4146-8679-f6ee2a921e2e.png)
>Server with 1 player and without Canary:
>![image](https://user-images.githubusercontent.com/125617084/220752554-02a2141c-cbad-4512-86f6-c2f20947c0fa.png)

**Comment by AbdElAziz333** [comment]
if you changed the mod from Radium to Canary can you please do the optimize world option (vanilla optimize world option)?

**Comment by Askes1s** [comment]
Ive never used Radium. In fact, I dont know what it is. Still, where could I find the Optimize World Option?

**Comment by AbdElAziz333** [comment]
can you test the latest update?, if the issue fixed in the new update please close the issue.
