### ISSUE TITLE
Crash on Startup canary-mc1.18.2-0.1.5

### ISSUE THREAD

**Issue by border999** [AbdElAziz333/Canary#109]
Canary just updated, couldn't use it before tried this new version and it's crashing to.
------------------------

### Version

> canary-mc1.18.2-0.1.5
> Forge: 1.18.2-forge-40.2.0

### Crash Report File

>latest.log https://gist.github.com/border999/1e57ceb8a622aa31227b4d9c876a58e1
>debug.log https://gist.github.com/border999/6e0226d93ccb4ce67b27701262e4e99a

**Comment by V972** [comment]
Same crash here
Same Minecraft and Forge version

[latest.log](https://github.com/AbdElAziz333/Canary/files/10889553/latest.log)
[debug.log](https://github.com/AbdElAziz333/Canary/files/10889554/debug.log)

**Comment by AbdElAziz333** [comment]
should be fixed in the 0.1.6 version, so sorry for that!

**Comment by SmallSansSerif** [comment]
Crash on player join on a dedicated server in 1.19.2 as well.
