### ISSUE TITLE
[1.18.2] Disconnected from Server

### ISSUE THREAD

**Issue by tharrmeehan** [AbdElAziz333/Canary#11]
### Version

canary-mc1.18.2-0.0.5
(Might be an incompatibility with Mowzies Mobs)

### Reproduction Steps

1.  Download canary and mowziesmobs 
2.  Walk around where Barako spawns (locate with /locate)
3.  Disconnected

### Crash Report File

[crash-2022-09-17_11.33.41-server.txt](https://github.com/AbdElAziz333/Canary/files/9591378/crash-2022-09-17_11.33.41-server.txt)

### Minecraft Save

Save too big :(

### Additional Information
No crashes on 0.0.1

**Comment by HavocJupiter** [comment]
> No crashes on 0.0.1

Does this also happen on 0.0.4?

**Comment by tharrmeehan** [comment]
> > No crashes on 0.0.1
> 
> Does this also happen on 0.0.4?

Yes, this also happens on 0.0.4.

**Comment by AbdElAziz333** [comment]
Its incompatibility with Mowzie's mobs Barako mobs spawn, i will try to fix this.

**Comment by AbdElAziz333** [comment]
fixed in both 1.19.2-0.0.3 and 1.18.2-0.0.7.
