### ISSUE TITLE
Crash of dedicated server on player join 1.19.2 with v0.1.9

### ISSUE THREAD

**Issue by SmallSansSerif** [AbdElAziz333/Canary#110]
canary-mc1.19.2-0.1.9
Forge 43.2.6

Updated from v0.1.8 and get an instant server crash when player joined. Crash report attached.
 
[crash-2023-03-04_20.40.07-server.txt](https://github.com/AbdElAziz333/Canary/files/10889677/crash-2023-03-04_20.40.07-server.txt)

**Comment by SmallSansSerif** [comment]
Any idea on this error? 

java.lang.RuntimeException: Attempted to load class com/mojang/blaze3d/vertex/PoseStack for invalid dist DEDICATED_SERVER

**Comment by AbdElAziz333** [comment]
The issue was fixed in the updated versions, Good Luck!
