### ISSUE TITLE
1.19.2 [Mod Compatibility] Hoppers Cannot Output to AE2's Inscriber and Charger

### ISSUE THREAD

**Issue by INFCode** [AbdElAziz333/Canary#117]
### Version Information

> canary-mc1.19.2-0.1.9
> AE2 12.9.2

### Expected Behavior

> Hoppers are supposed to be able to output to AE2's Inscribers and Chargers as long as the items in the hopper match the required input type and there is an empty slot in the machine. This is also the behavior if you only install AE2 without Canary.

### Actual Behavior

> Hoppers outputs only when there are updates to the hopper, e.g. the items in the hopper are changed, the hopper is locked and then unlocked by redstone signal, or there are items thrown/picked up near the hopper. The hopper seems also rarely outputs correctly without updates because I sometimes find the AE2 machine generates products if I am away for a while, but I never observe how this happens, which I guess might be because of the random tick.

### Reproduction Steps

> 1. Put the charger in AE2 in the middle and 2 hoppers from above and behind. Use Certus Quartz Wrench right-click in the front to rotate it 90 degrees clockwise.
> 2. Put a vibration chamber behind the charger and add charcoals in it, or connect other power sources from other mods. 
> 3. Put Certus Quartz Crystals in the hopper on the top. Then one crystal will be inserted into the charger, but not the rest. you can update the hopper and one more crystal will be output.

### Other Informat
![2023-03-21_23 39 05](https://user-images.githubusercontent.com/32475763/226796110-b22c2f1a-f89f-4447-ab30-c53c9bdf5eab.png)
The machine to reproduce the issue.

**Comment by AbdElAziz333** [comment]
Can you please test without Canary? i tested it and the issue in the Charger block itself.
