### ISSUE TITLE
Hyperlink on Pluto Curseforge page links to here instead of Pluto issue page

### ISSUE THREAD

**Issue by Zenrex** [AbdElAziz333/Canary#118]
### Version Information

> No version.

### Expected Behavior

> The purple hyperlink that says 'here' on Pluto the Curseforge page should link to https://github.com/AbdElAziz333/Pluto/issues

### Actual Behavior

> The purple hyperlink that says 'here' on Pluto the Curseforge page links to https://github.com/AbdElAziz333/Canary/issues

### Reproduction Steps

Type 'Pluto Curseforg' on Google.com.

![Screenshot 2023-03-26 031329](https://user-images.githubusercontent.com/103629189/227750004-203f2213-413a-4a65-b00e-2365b09e4154.png)

Click on the first search result.
![Screenshot 2023-03-26 031404](https://user-images.githubusercontent.com/103629189/227750033-4f2d828e-657e-452c-81ca-bd5f6be15718.png)

Click on the hyperlink that says 'here'
![Screenshot 2023-03-26 031423](https://user-images.githubusercontent.com/103629189/227750072-cf2278c2-6267-416b-bdaa-8a211b9617b3.png)

### Other Information

> On [Modrinth](https://modrinth.com/mod/pluto) there is no hyperlink it's just regular text.
![Screenshot 2023-03-26 032050](https://user-images.githubusercontent.com/103629189/227750158-86983cb6-78be-490b-9020-251a9c89a947.png)

**Comment by AbdElAziz333** [comment]
fixed.
