### ISSUE TITLE
Crash with 0.0.5

### ISSUE THREAD

**Issue by Atlantispy** [AbdElAziz333/Canary#12]
### Version

canary-mc1.18.2-0.0.5
1.18.2
Forge 40.1.80

### Reproduction Steps
> 1. Launch game
> 2. Leave running
> 3. Crash

### Crash Report File
[crash-2022-09-17_15.07.42-server.txt](https://github.com/AbdElAziz333/Canary/files/9591867/crash-2022-09-17_15.07.42-server.txt)

**Comment by AbdElAziz333** [comment]
duplicate of #11.

**Comment by AbdElAziz333** [comment]
fixed in both 1.19.2-0.0.3 and 1.18.2-0.0.7.
