### ISSUE TITLE
Dedicated Server crashes on exception (with Create Mod)

### ISSUE THREAD

**Issue by jang1er** [AbdElAziz333/Canary#123]
### Version
 canary-mc1.19.2-0.1.9

### Reproduction Steps
Example:
1. Build any contraption with a gantry shaft (specifically: https://createmod.com/schematics/improved-infinite-experience-generator)
2. Connect power to top level mechanism
3. Server instantly crashes

### Crash-Log
[crash-2023-04-10_20.13.08-server.txt](https://github.com/AbdElAziz333/Canary/files/11193116/crash-2023-04-10_20.13.08-server.txt)

**Comment by JumboYumbo** [comment]
happened to me too, except it happens whenever I ponder a basin. https://bytebin.lucko.me/15n6UqYDjf

**Comment by AbdElAziz333** [comment]
can you please use the new update?
[1.19.4](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4498538) - [1.19.3](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4498537) - [1.19.2](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4498536) - [1.18.2](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4498539)

**Comment by jang1er** [comment]
To further clarify: The Server crashes the instant when create carriages are being **moved**, not when they are just placed or exist as blocks in the world. When the server is restarted the affected contraption is completly removed from existence.

**Comment by Yourname942** [comment]
Is there a config option that will make that not crash? (to toggle off whatever is affected by it) - as a temporary solution

**Comment by Tyrantosaurex** [comment]
Hey there, I thought I'd chime in that this isn't Create specific - it'll hit on any ticking entity that it doesn't seem to like (Had a mob in the Twilight Forest causing the same crash). Modpack creators are still good to have it client side however. It's just not tenable to have it severside when it deletes the offending ticking entity.

**Comment by KostromDan** [comment]
On the today released version still crashes.
https://github.com/AbdElAziz333/Canary/issues/132
[crash-2023-05-15_13.30.08-server.txt](https://github.com/AbdElAziz333/Canary/files/11476829/crash-2023-05-15_13.30.08-server.txt)
[debug.log](https://github.com/AbdElAziz333/Canary/files/11476841/debug.log)
[latest.log](https://github.com/AbdElAziz333/Canary/files/11476842/latest.log)

**Comment by AbdElAziz333** [comment]
can you try please add mixin.entity.collisions.intersection=false in the config ?

**Comment by KostromDan** [comment]
> can you try please add mixin.entity.collisions.intersection=false in the config ?
Smth changed, but still crash
[crash-2023-05-15_21.35.47-server.txt](https://github.com/AbdElAziz333/Canary/files/11480907/crash-2023-05-15_21.35.47-server.txt)
[debug.log](https://github.com/AbdElAziz333/Canary/files/11480912/debug.log)
[latest.log](https://github.com/AbdElAziz333/Canary/files/11480913/latest.log)

**Comment by AbdElAziz333** [comment]
can you please try mixin.entity.collisions.movement=false in the config util i release a version to fix this ?

**Comment by jang1er** [comment]
> can you please try mixin.entity.collisions.movement=false in the config util i release a version to fix this ?

Tried it. Still the same crash issue.
Crash report: https://pastebin.com/umkUaPXz

**Comment by AbdElAziz333** [comment]
Okay per testing, you can add those 2 lines into the config fiile until i release a fix.
mixin.entity.collisions.movement=false
mixin.entity.collisions.interesction=false

**Comment by AbdElAziz333** [comment]
can you please use the new update?
[1.19.4](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4549998) - [1.19.3](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4550001) - [1.19.2](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4550002) - [1.18.2](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4550004)
