### ISSUE TITLE
Server carsh when i around the Iron Farm [MC 1.19.2][Canary v0.1.10]

### ISSUE THREAD

**Issue by ElfPlayer** [AbdElAziz333/Canary#127]
At the Canary v0.1.9 i go to the Iron Farm the server will not carsh,but when i update mod version to v0.1.10 the server will carsh
[crash-2023-04-21_20.21.39-server.txt](https://github.com/AbdElAziz333/Canary/files/11296076/crash-2023-04-21_20.21.39-server.txt)

**Comment by Jimjamss** [comment]
^ same as above - tested by rolling back Canary to V0.1.9 and it fixed - I know it is a client and/or server sided mod - I rolled back the update to V0.1.9 from V0.1.10 only on the server to see if it fixed (it did) but I left V10 on my client (am lazy) and was able to test out to see if it would still crash using the crate ponder when using v10 on my client but the server having v9 and pondering did not cause an issue _and_ the iron farm did not cause a crash for me when I loaded the chunk. 
[crash-2023-04-28_22.53.46-server.txt](https://github.com/AbdElAziz333/Canary/files/11357787/crash-2023-04-28_22.53.46-server.txt)

**Comment by AlexeyZavar** [comment]
Same issue here, but with gold farm.

Fixed by putting this in `canary.properties`:

```
mixin.block.hopper=false
block.hopper=false  # idk if this one required
```

**Comment by AbdElAziz333** [comment]
can you please use the new update?
[1.19.4](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4549998) - [1.19.3](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4550001) - [1.19.2](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4550002) - [1.18.2](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4550004)
