### ISSUE TITLE
[1.19.2] Crash when entering Dimensional Dungeons using the Keys.

### ISSUE THREAD

**Issue by Gbergz** [AbdElAziz333/Canary#128]
### Version
MC: 1.19.2
Canary: v0.1.10
Forge: 43.2.8

### Reproduction Steps
> 1. Use a Blank Portal Key on a Key Inscribing Station
> 2. Use the produced key on a Portal Keystone in a fully built portal
> 3. 50/50 chance a server crash happens it seems.

Profit.

### Crash Report File
https://gist.githubusercontent.com/Gbergz/da12256ff68eb635ce69873373680c68/raw/4a9ed2058cb6245dfe4d82671876d61251a58488/gistfile1.txt

### Additional Information
From a user:
Interesting tidbit, once the server recovers from a crash, I load in and the portal is generated as if there is nothing wrong.

### Note:
This is a cross interaction crash with Dimensional Dungeons mod.
Link: https://www.curseforge.com/minecraft/mc-mods/dimensional-dungeons
Mod version: 168- 1.19.0

**Comment by AbdElAziz333** [comment]
can you please use the new update?
[1.19.4](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4549998) - [1.19.3](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4550001) - [1.19.2](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4550002) - [1.18.2](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4550004)

**Comment by Gbergz** [comment]
Will give it a try next few days and post an update here once I can

**Comment by Gbergz** [comment]
So, the newest update won't let me boot the client anymore. (v0.2.2)

Using 0.2.0 works fine.

**Comment by AbdElAziz333** [comment]
can you use this?
[1.19.2](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4550539)

**Comment by Gbergz** [comment]
Will give it a go in an hour or two
