### ISSUE TITLE
Hopper Issue

### ISSUE THREAD

**Issue by TQCnoARosto** [AbdElAziz333/Canary#129]
### Version

Forge - 43.2.8
canary-mc1.19.2-0.1.10.jar

### Crash Report File

https://pastebin.com/ZYLF1aK2

### Additional Information

I connected a hopper to a block of another mod (Intelligence: Quarry), and after a few seconds the world crashed, furthermore it is not possible to reopen the world because the problem persists. I assume this behaviour is given by the Canary mod from this line: 
"java.lang.ClassCastException: class net.minecraft.server.level.ServerLevel cannot be cast to class com.abdelaziz.canary.common.world.blockentity.BlockEntityGetter".

Did I miss any steps? Are there any configurations that i haven't set in the best way or is this a bug?

**Comment by Tekunogosu** [comment]
I had this same issue with 1.10, I rolled back to 1.9 and it works just fine. Hopefully next update works.

**Comment by TQCnoARosto** [comment]
In fact in the changelog it says "- Replace @Redirect with @Inject to optimize the hopper code.", so actually they changed the hopper code, maybe they forgot to handle some exception(s).

**Comment by TQCnoARosto** [comment]
Solved with patch (canary-mc1.19.2-0.2.0) witch removes the hopper changes ("Hi, this update removes the hopper block entity only and block entity sleeping optimizations as them unstable and create incompatibilities
with other mods.")
