### ISSUE TITLE
Villagers cannot reproduce

### ISSUE THREAD

**Issue by ShamHyper** [AbdElAziz333/Canary#134]
### Version Information

canary-mc1.19.4-0.1.10
Minecraft 1.19.4
Forge - 45.0.57 (tested on 45.0.56-45.0.59)

### Expected Behavior

The ability of villagers to reproduce

### Actual Behavior

Villagers can't reproduce, I conducted a lot of tests and built auto-firms, they don't reproduce with the mod, as soon as I turn off the mod, I immediately see millions of children :)

### Reproduction Steps

1. Go to village
2. Gived food and beds to them
3. Bruh moment

**Comment by Mrnar1s** [comment]
They also have many problems path-finding and moving in general, they move a lot less and also might stop mid-way to their job station.

**Comment by Mrnar1s** [comment]
And Farmers don't farm

**Comment by lemorage** [comment]
The same problem at 1.20.1.

**Comment by Sas0ni** [comment]
I have the same problem when using this mod, they wont move or restock.

**Comment by SkpC9** [comment]
Villagers also won't breed

**Comment by AbdElAziz333** [comment]
can you please try the new update?
