### ISSUE TITLE
[1.19.2] Crash when flowing fluid touches Hopper input or output edge

### ISSUE THREAD

**Issue by samuel-hunter** [AbdElAziz333/Canary#138]
### Version Information

- Minecraft 1.19.2
- Canary 0.2.0
- Forge 43.2.0 and 43.2.7

Reproducible with no other mods installed.

### Actual Behavior

When a fluid flows to the top of a Hopper, or the output edge of a Hopper, either the server crashes if on Multiplayer, or if on Singleplayer, the entire game crashes (not just its internal server) with a `Caused by: java.lang.ClassCastException: class net.minecraft.server.level.ServerLevel cannot be cast to class com.abdelaziz.canary.common.world.blockentity.BlockEntityGetter`.

Even more strange, after the hopper and fluid is cleaned up, then any block that is at the position of the old hopper, once broken, suppresses the same Exception, and the block item is not dropped.

### Reproduction Steps

1. Place a water bucket two blocks above a hopper
2. Wait for water to flow down

Or:

1. Place a water bucket two blocks manhattan distance away from the output side of a hopper
2. Wait for water to flow to the hopper

### Other Information

- [Client log](https://mclo.gs/De0dPwk) generated on crash
- [Backtrace on server](https://mclo.gs/Us2TcMc) when placing, breaking block where Hopper used to be

Here's all the experiments I've done:

- Forge 43.2.0; flow water to hopper top: **CRASH**
- Forge 43.2.7; flow water to hopper top: **CRASH**
- Forge 43.2.0; flow water to (non-output) hopper side: **OK**
- Forge 43.2.0; flow water to (non-output) hopper bottom: **OK**
- Forge 43.2.0; flow water to (output) hopper side: **CRASH**
- Forge 43.2.0; flow water to (output) hopper bottom: **CRASH**
- Forge 43.2.0; place water source directly above hopper top: **OK**
- Forge 43.2.0; reload crashed world, remove water source, and wait for flowing water to dissipate: **CRASH**
- Forge 43.2.0; flow lava to hopper top: **CRASH**

**Comment by HijackHornet** [comment]
I have the same error on a brand new world. I cant even get to join it after generation.

**Comment by davidromrell** [comment]
same issue, mine was influenced by an interaction with ferritecore.
