### ISSUE TITLE
crash at launch 1.19.2 forge, canary 0.2.2

### ISSUE THREAD

**Issue by tenzedkariyu19** [AbdElAziz333/Canary#145]
------------------------

Version: 

canary-mc1.19.2-0.2.2.jar

### Reproduction Steps

launch game

### Crash Report File
[latest.log](https://github.com/AbdElAziz333/Canary/files/11550267/latest.log)
[crash-2023-05-23_20.59.14-client.txt](https://github.com/AbdElAziz333/Canary/files/11550269/crash-2023-05-23_20.59.14-client.txt)

works fine with canary-mc1.19.2-0.2.0.jar

**Comment by Branjoman** [comment]
Can confirm I get a similar crash to this one, crash log for reference: https://pastebin.com/qC0Prg0g

**Comment by AbdElAziz333** [comment]
can you use this?
[1.19.2](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4550539)

**Comment by Branjoman** [comment]
That link doesn't appear to work.
