### ISSUE TITLE
[1.18.2] Ticking entity  java.lang.IllegalStateException: stream has already been operated upon or closed

### ISSUE THREAD

**Issue by Reshy** [AbdElAziz333/Canary#146]
### Version

canary-mc1.18.2-0.1.10.jar

### Reproduction Steps

1. Install Canary
2.  Generate New World

### Crash Report File

https://pastebin.com/VbrN8zPu

**Comment by AbdElAziz333** [comment]
can you use this?
[1.19.2](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4550539)

**Comment by AbdElAziz333** [comment]
The issue was fixed in the updated versions, 0.2.0 for 1.18.2, and 0.2.3 for 1.19.+, good luck!
