### ISSUE TITLE
Latest canary version causes crash when creating fluids using KubeJS

### ISSUE THREAD

**Issue by TheDrOfDoctoring** [AbdElAziz333/Canary#147]
### Version Information

Canary-mc1.19.2-0.2.2
Relevant KubeJS and architectury versions: kubejs-forge-1902.6.0-build.142, architectury-6.5.8.2-forge

### Expected Behavior

Registering fluids with KubeJS and Canary shouldn't crash the game

### Actual Behavior

Registering fluids with KubeJS crashes the game with latest canary version, which does not occur on canary 0.2.0
### Reproduction Steps

1 - Add this script to a file in the startup scripts folder of KubeJS (Directory is `packfolder/kubejs/startup_scripts`):
```
StartupEvents.registry("fluid", event => {
	event.create('soul_fluid')
	.displayName('Soul Fluid')
	.thickTexture(0xFFFFFF)
	.bucketColor(0xFFFFFF))
})
```
2 - Game will crash with similar crash report on launch to the one attached. This does not occur with version 0.2.0 of canary.
### Other Information

[crash-2023-05-24_11.51.24-client.txt](https://github.com/AbdElAziz333/Canary/files/11552061/crash-2023-05-24_11.51.24-client.txt)

**Comment by AbdElAziz333** [comment]
can you use this?
[1.19.2](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4550539)

**Comment by TheDrOfDoctoring** [comment]
Fixed, thanks!
