### ISSUE TITLE
[1.18.2]Mowzie's Mobs sunstrikes cause server lag

### ISSUE THREAD

**Issue by 6371peter** [AbdElAziz333/Canary#15]
Version
canary-mc1.18.2-0.0.7
mowziesmobs-1.5.29
Forge-1.18.2-40.1.80

Reproduction Steps
 1.Download canary and mowziesmobs
 2.Find Barako spawns
 3.Make Barako use sunstrike,then server lag

**Comment by AbdElAziz333** [comment]
duplicate of #11 and #12.

**Comment by AbdElAziz333** [comment]
Sorry, its not duplicate issue, i will look into this.

**Comment by AbdElAziz333** [comment]
for now you can set `mixin.entity.fast_retrieval=false` in canary.properties in the config file.

**Comment by AbdElAziz333** [comment]
fixed in the coming version.

**Comment by AbdElAziz333** [comment]
The issue is fixed in both 0.1.1 for MC 1.19.2 and 0.0.10 for MC 1.18.2.
I hope you have a good day!
