### ISSUE TITLE
[1.19.2] Crashes with Inventorio

### ISSUE THREAD

**Issue by No1129** [AbdElAziz333/Canary#150]
### Version
canary-mc1.19.2-0.2.3

### Reproduction Steps

game crashes on boot when loaded with Inventorio
### Crash Report File

https://file.garden/Yjp9XGA2LRQTk7Ha/latest.log
https://file.garden/Yjp9XGA2LRQTk7Ha/debug.log

### Additional Information

Inventorio mod link
https://www.curseforge.com/minecraft/mc-mods/inventorio-forge

**Comment by Reshy** [comment]
It also happens on the 1.18.2 version.  The developer of Inventorio said this:

https://github.com/Lizard-Of-Oz/Inventorio/issues/242#issuecomment-1573553078

> Incompatibility with the Canary mod.
> Impossible to solve on my end, but the optimization Canary does [at the point of mod conflict](https://github.com/AbdElAziz333/Canary/blob/6f56b87cc44304d0ed96817c3637df3984b1fe3c/src/main/java/com/abdelaziz/canary/mixin/calc/if_else/player_slot/PlayerMixin.java#L52) is by all means and purposes negligible, they could simply remove that mixin. It will solve the issue and have basically 0 impact.
> `Alternatively,` they could set that overwrite optional and set its priority lower than [Inventorio's mixin here](https://github.com/Lizard-Of-Oz/Inventorio/blob/d40f728c3b74616a8541b22ea45e4396641ab4bc/common/src/main/java/me/lizardofoz/inventorio/mixin/PlayerEntityMixin.java#L61) would have priority (we both went with exactly 1000, what a coincidence)

**Comment by AbdElAziz333** [comment]
does it still happens in 0.2.4 versions in 1.19.x or in the 0.2.1 version of 1.18.2 of Canary?

**Comment by Reshy** [comment]
> does it still happens in 0.2.4 versions in 1.19.x or in the 0.2.1 version of 1.18.2 of Canary?

I'll need to test, the issue isn't easy to replicate so it's hard to tell if I'm failing to replicate it or if the new version patched it.

**Comment by AbdElAziz333** [comment]
Can you please try the new update, good luck!

**Comment by laboriens** [comment]
hello, the problem returned with canary-mc1.20.1-0.3.3
