### ISSUE TITLE
server crash when entering twilight forest

### ISSUE THREAD

**Issue by Chaz-Pat** [AbdElAziz333/Canary#153]
MC Version: 1.19.2
Canary Version: 1.19.2-0.2.0
Twilight Forest Version: 1.19.2-4.2.1518
Java Version: 17.0.2

Crash: Exception in server tick loop

Report: https://cdn.discordapp.com/attachments/1107750788840824964/1111600861555204187/crash-2023-05-26_11.14.02-server.txt

**Comment by IaonnisPrysma** [comment]
Having the same issue, also happens with Radium, which is also a fork of Lithium so I suppose this might be a Lithium issue tbh, could it be solved by Canary dev?

**Comment by AbdElAziz333** [comment]
Can you please try the new update, good luck!

**Comment by Chaz-Pat** [comment]
Hello, No crashes so far with latest update. Thanks
