### ISSUE TITLE
[1.19.4] Crash when entering area with villagers in boat

### ISSUE THREAD

**Issue by Schmille** [AbdElAziz333/Canary#156]
### Version

> Example: canary-mc1.19.4-0.2.4

### Reproduction Steps

> 1. Enter an area a villager in a boat
> 2. Game crashes

This issue was discovered when playing on a dedicated server, though the problem persists in singleplayer. 
Trying to reconnect to the server leads to another crash.
Upon removing or renaming the canary jar file - thus disabling the mod - the issue no longer occurs.

### Crash Report File
[Gist](https://gist.github.com/Schmille/5f1bad0bcd1b740310b0563ea1e5c520)

### Minecraft Save

> As there appear to be no specific conditions, any world will do. 
The attached zip contains a superflat world with a boat and a villager spawn egg in hand.

[Recreation.zip](https://github.com/AbdElAziz333/Canary/files/11594033/Recreation.zip)

**Comment by AbdElAziz333** [comment]
Can you please try the new update, good luck!

**Comment by Schmille** [comment]
Thank you! I could not reproduce the issue using version 1.19.4-0.2.6.
