### ISSUE TITLE
Stuttering Mobs

### ISSUE THREAD

**Issue by Pineappleguy03** [AbdElAziz333/Canary#16]
Newest Canary Version 0.0.6

Creepers and some mobs now have stuttering movement. Like they move with a stuttering movement and it's odd.

**Comment by Pineappleguy03** [comment]
Hope this is fixed soon.

**Comment by AbdElAziz333** [comment]
did you used the 0.0.7 version instead of 0.0.6?

**Comment by Pineappleguy03** [comment]
No. I shall check now.

**Comment by Pineappleguy03** [comment]
It is still happening

**Comment by Pineappleguy03** [comment]
Now it's also happening for players

**Comment by Pineappleguy03** [comment]
it was running 360 TICKS BEHIND. Very bad.

**Comment by AbdElAziz333** [comment]
Can you send me an image or video?, i tested 0.0.6 , 0.0.7 but i don't understand what you mean by stuttering movement.

**Comment by Pineappleguy03** [comment]
Like when you spawn in everything is much faster as per usual. But like imagine when you see a cow for example. When the servers tick time is going VERY SLOWLY. The mobs move like very slowly like everything is in slow motion. So if I hit a Mob it very slowly moves back instead of instantly going back. Or when I broke a block it took a few seconds to break.

**Comment by Pineappleguy03** [comment]
Basically the tick time was terrible so everything was processing super slowly

**Comment by Pineappleguy03** [comment]
Can you not replicate the issue?
