### ISSUE TITLE
Crashing with latest canary 

### ISSUE THREAD

**Issue by KarinMiku** [AbdElAziz333/Canary#160]
### Version
Latest version: canary-mc1.18.2-0.2.2

### Reproduction Steps
Crashing after trying to enter the Nether, didn't test much but i assume this is an issue that might happen after trying to go to any other dimension too

### Crash Report File

[crash-2023-06-14_13.13.51-server.txt](https://github.com/AbdElAziz333/Canary/files/11749391/crash-2023-06-14_13.13.51-server.txt)

### Additional Information

Previous version works without issues
Forge v40.2.0

**Comment by Gantros** [comment]
I too have this problem for 1.19.2 version:
Forge 43.2.14
Canary v0.2.5

https://pastebin.com/dl/7vjZRQQb

**Comment by Redls07** [comment]
1.19.2, Canary 0.2.6, the problem still remains
[crash-2023-06-15_19.32.50-server.txt](https://github.com/AbdElAziz333/Canary/files/11757520/crash-2023-06-15_19.32.50-server.txt)

**Comment by Redls07** [comment]
Fixed with 0.2.7
