### ISSUE TITLE
Player gets kick out when trying to load the Nether via using a portal

### ISSUE THREAD

**Issue by laurasharp** [AbdElAziz333/Canary#162]
### Version

canary-mc1.19.2-0.2.7.jar

### Reproduction Steps
> I had canary installed on server and client side
> made a nether portal and when going through the portal it would kick out player
> got the nether to load if the player use the command: /execute in The_Nether run teleport Slartiblockfast 100 100 100 while in spectator mode 

> Removed Canary from server side per another modder's recommendation from reviewing the crash report and the was able to load the nether via the portal.

### Crash Report File

Here are the two logs:
https://paste.ee/p/ysGMk (Client Side Log)
https://paste.ee/p/6stve (Server Side Log)

### Additional Information

Crash does not happen when Canary is uninstalled

**Comment by AbdElAziz333** [comment]
You are using Canary 0.2.5, please update to the latest update.
