### ISSUE TITLE
Crashing when entering the nether

### ISSUE THREAD

**Issue by RalkeyOfficial** [AbdElAziz333/Canary#163]
### Version

canary-mc1.19.2-0.2.6
### Reproduction Steps

1. start a survival world.
2. create a nether portal.
3. not profit.

### Crash Report File

[crash-2023-06-29_21.48.36-server.txt](https://github.com/AbdElAziz333/Canary/files/11909554/crash-2023-06-29_21.48.36-server.txt)

### Minecraft Save

N/A, don't have access to the save file

### Additional Information

My friend is hosting a single player world via Essentials mod. We use a custom mod pack containing Create.
When we try to enter the nether, his game crashes.
Once disabling Canary, it all works again.

**Comment by Collinnation** [comment]
Having the same issue with canary on my server that I'm hosting for me and my friends
[crash-2023-07-11_21.41.01-server.txt](https://github.com/AbdElAziz333/Canary/files/12023668/crash-2023-07-11_21.41.01-server.txt)

**Comment by AbdElAziz333** [comment]
You are using Canary 0.2.6, please update to the latest update.
