### ISSUE TITLE
Villagers dont move when using mod on forge server

### ISSUE THREAD

**Issue by Sas0ni** [AbdElAziz333/Canary#165]
Version,
Using version "Canary 0.2.6 for MC 1.20(.1)" and server uses "Forge 47.1.3"

Villagers will move 2 seconds after joining game and then they will freeze. Though they will come to you if you interact with them and when you hit them. Sometimes they will go to sleep sometimes not. Villagers work fine when not using canary, I dont know if this is only on my server, maybe working on other servers. Hope to get some answers soon. Thank you, kind regards Sasoni.

**Comment by AlexPotato115** [comment]
After so long trying to find the culprit, I can confirm that villagers don't really do anything with this mod. I'm using 1.20.1, and they can't breed, restock, interact with other villagers, or even pathfind correctly. Hoping for a fix soon, mod has delivered on the other features and made my game stable.

**Comment by loglob** [comment]
Can confirm. Adding `mixin.ai = false` to the config file fixed it for me.

**Comment by TonnaChan** [comment]
I have also come to the same conclusion as OP, that Canary is causing villager farmers to not harvest, plant, and share harvest.

**Comment by sanyaysan** [comment]
After some testing I have narrowed the issue down to `mixin.ai.task.replace_streams`. Setting this rule to false in the config file will fix the issue

**Comment by AbdElAziz333** [comment]
can you please try the new update?

**Comment by loglob** [comment]
> can you please try the new update?

updating to version 0.2.7 fixed it, thanks

**Comment by Darkmega18** [comment]
is this change also in 1.19.2? I believe I might have issues related to this on my server, since we have a librarian and some others who're not really shuffling their trades all that much upon being leveled up in the dynamic villager trades mod.

**Comment by Lerrycapetime** [comment]
still a bug for me in the latest 1.20.1 Version 0.2.7
Have to open the properties config and enter mixin.ai.task.replace_streams = false

**Comment by AbdElAziz333** [comment]
can you please try the new update?
