### ISSUE TITLE
[1.19.2] Crash on Load with Modern Fix + Effortless Building

### ISSUE THREAD

**Issue by Reshy** [AbdElAziz333/Canary#166]
### Version

![image](https://github.com/AbdElAziz333/Canary/assets/2096384/1bd796d1-36fc-440e-93d3-f75f96411980)

### Reproduction Steps

> 1. Install Canary, Modern Fix, and Effortless Building.
> 2. Boot Minecraft.
> 3. Crash on Load.

### Crash Report File
https://pastebin.com/4fyZV7KC

**Comment by Reshy** [comment]
This also can happen with Create in conjunction with some other mod I can't figure out.

**Comment by AbdElAziz333** [comment]
can you please try the new update?

**Comment by SiverDX** [comment]
can canary affect loaded dependencies or is this just not related to canary?

``` log
[23Jul2023 05:49:21.699] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'flywheel', Requested by: 'effortlessbuilding', Expected range: '[0.6.9,0.6.10)', Actual version: '[MISSING]'
```

https://bitbucket.org/Requios/effortless-building/src/1.19/src/main/resources/META-INF/mods.toml
https://bitbucket.org/Requios/effortless-building/issues/194/mod-effortless-building-requires-flywheel

the mixin error might actually not be a real error - i had that happen before and once i added a missing dependency / fixed an error which happend prior to the mixin one, the mixin error disappeared

this is probably related to forge crashlogs being absolutely useless

**Comment by AbdElAziz333** [comment]
I think this issue is fixed in the updated releases of ModernFix, if it still happens, please open a new issue, good luck.
