### ISSUE TITLE
[1.18.2]Creepers never flee from ocelots and cats

### ISSUE THREAD

**Issue by 6371peter** [AbdElAziz333/Canary#17]
### Version Information
Forge-1.18.2-40.1.80
canary-mc1.18.2-0.0.7

### Expected Behavior
Creepers flee from ocelots and cats within a 6-block radius, with faster movement than when pursuing a player.;
Skeletons flee from wolves.;

### Actual Behavior
Creeper just walk around,it never flee from ocelot and cats;
Skeleton also not flee wolf.

### Reproduction Steps
1.Summon creeper and ocelot(Use command or spawn egg)
2.Observe creeper behavior.

### Other Information
Piglin will run away from nearby zoglins or nearby zombified piglins.

**Comment by AbdElAziz333** [comment]
this issue is happens only with the creepers, i will look into that.

**Comment by AbdElAziz333** [comment]
fixed in the new update, and if you want 1.18.2 maybe it will be released tomorrow, good luck!
