### ISSUE TITLE
Create fails to load with Canary 1.19.2

### ISSUE THREAD

**Issue by Hexnet111** [AbdElAziz333/Canary#171]
**Version:**
canary-mc1.19.2-0.2.8

**Reproduction Steps:**
1. Install Canary
2. Install Create
3. Launch the game
4. Create fails to load with "java.lang.reflect.InvocationTargetException: null"

**Crash Report File** (I'm using other mods, so sorry if it's more cluttered.):
[‏‏latest.log](https://github.com/AbdElAziz333/Canary/files/12342289/latest.log)

**Additional Information:**
One solution I found that works is loading the game without Canary first, then shutting it down, putting Canary back, and reloading the game. This for some reason fixes the issue, although only temporarily.

**Comment by M4ximumPizza** [comment]
Based on the crash report you provided, it appears that Canary is failing to recognize the MovementBehaviour class. Furthermore, it is neglecting to acknowledge the presence of associated elements within it, such as blocks and textures. This issue extends to the point of missing textures, despite their expected presence. This indicates a potential compatibility problem between the mods and Canary, which could stem from either incompatible mod versions or improper functioning. Evidently, there are multiple factors contributing to the sequence of errors culminating in the eventual crash.

**Comment by Hexnet111** [comment]
Yeah, apparently some of my friends started having the same issue with other mods. Although, since it only sometimes happens, we just restart the game a couple of times to fix it.

**Comment by M4ximumPizza** [comment]
I would assume with the texture problems. But restarting the game does do something with it. I don't know what though.

**Comment by StormDragon-64** [comment]
- Canary isn't causing the MovementBehaviors error, Chisels and Bits is.
- The crash happens because Create's mod instance fails to be created
- When reporting an incompatibility, make sure to try it with just the mods in question too, so in this example, you would try it with just Canary and Create.
