### ISSUE TITLE
Canary causes huge TPS lag

### ISSUE THREAD

**Issue by Pineappleguy03** [AbdElAziz333/Canary#18]
Canary 0.0.7 Integrated Server

If you watch the tick time of your server the tick goes well into 400 Tick per second.

**Comment by Pineappleguy03** [comment]
Oh yeah this issue is where the struering mobs issue stems from.

**Comment by Pineappleguy03** [comment]
Stutter*

**Comment by AbdElAziz333** [comment]
You have this issue with only Forge and Canary or with other mods ?

**Comment by Pineappleguy03** [comment]
I have with other mods

**Comment by AbdElAziz333** [comment]
can you send me them, you can find the mods in the latest.log in .minecraft/logs.

**Comment by Pineappleguy03** [comment]
One second!

**Comment by Pineappleguy03** [comment]
WTF I FIXED IT. Ok then... Nvm then???

**Comment by Pineappleguy03** [comment]
NO ITS NOT.
[latest.log](https://github.com/AbdElAziz333/Canary/files/9719565/latest.log)
[debug.log](https://github.com/AbdElAziz333/Canary/files/9719566/debug.log)

**Comment by Pineappleguy03** [comment]
Ok here's the file @AbdElAziz333

**Comment by Pineappleguy03** [comment]
Wait why is this closed was it fixed?

**Comment by Pineappleguy03** [comment]
Issue is still here.

**Comment by AbdElAziz333** [comment]
Could you please test with only Canary and Forge? this issue is not from Canary from what i see.

**Comment by Pineappleguy03** [comment]
But here's the thing 0.0.1 doesn't have these issues. With all of my mods I have.

**Comment by AbdElAziz333** [comment]
Yes because Canary 0.0.1 doesn't apply all the mixins to the game, i need the full mod list to know which compatibility is destroyed between Canary and the other mods.

**Comment by Pineappleguy03** [comment]
I think this might Help?

[Mods and computer Info.txt](https://github.com/AbdElAziz333/Canary/files/9769217/Mods.and.computer.Info.txt)

**Comment by embeddedt** [comment]
This might be https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/684.

**Comment by Pineappleguy03** [comment]
But the wither storm is not even active. I don't do it till the end

**Comment by embeddedt** [comment]
The lag occurs even if the wither storm is not active.

**Comment by Pineappleguy03** [comment]
Huh... Lemme try.

**Comment by nonamecrackers2** [comment]
Duplicate of #684. Both a fork of Lithium.

**Comment by nonamecrackers2** [comment]
I believe a certain config option fixed this, however not sure which one exactly.

**Comment by nonamecrackers2** [comment]
Yep, putting `mixin.ai.nearby_entity_tracking=false` in the `canary.properties` folder fixes the lag.

**Comment by Pineappleguy03** [comment]
It was wither storm. Just make sure to put a mod incompatibility.
