### ISSUE TITLE
[1.20.1] crash without crash report

### ISSUE THREAD

**Issue by MundM2007** [AbdElAziz333/Canary#187]
### Version
canary-mc1.20.1-0.2.7.jar

### Reproduction Steps
I'm using a quite intensive mod list (106 mods), where the crash just happens when you start the game and I'm only reporting with this many mods because it is really wierd and doesn't have any info really. Removing Canary fixes the issue.
if this is the wrong place to report please tell me and I'll move.
Modlist (renamed html file):
[modlist.txt](https://github.com/AbdElAziz333/Canary/files/13504387/modlist.txt)

### Crash Report File
No crash report file only log
[2023-11-29-1.log](https://github.com/AbdElAziz333/Canary/files/13504358/2023-11-29-1.log)
[debug-1.log](https://github.com/AbdElAziz333/Canary/files/13504365/debug-1.log)

**Comment by anapiadarkus** [comment]
Incompatibility with radium reforged. Removing it solved the same issue for me.

**Comment by MundM2007** [comment]
Didn't know I opened this, yeah radiuma nd Canary are Ports of the exact Same mods iirc and as such aren't compatable

**Comment by MundM2007** [comment]
Didn't know I opened this, yeah radiuma nd Canary are Ports of the exact Same mods iirc and as such aren't compatable
