### ISSUE TITLE
Canary mc conflicts with create mod ponder.

### ISSUE THREAD

**Issue by Pedgux** [AbdElAziz333/Canary#188]
### Version

canary-mc1.19.2-0.1.9.jar

### Reproduction Steps

1.Find any create ponder which has a item (item on ground) in it. For example the crushing wheel which has a item on it. Gold which gets dropped to the wheels.
2.Ponder it.
3.Wait until a item appears
4. crash

### Crash Report File

[crash-2023-12-09_20.41.25-client.txt](https://github.com/AbdElAziz333/Canary/files/13626056/crash-2023-12-09_20.41.25-client.txt)

### Minecraft Save

Save too big. Mod folder too big.

If you need mod list it's here :
AI-Improvements-1.19.2-0.5.2.jar
architectury-6.5.69-forge.jar
canary-mc1.19.2-0.1.9.jar
cloth-config-8.2.88-forge.jar
create-1.19.2-0.5.0.i.jar
create_enchantment_industry-1.19.2-for-create-0.5.0.i-1.1.14.jar
Create_Theme_Armor_Addon_1.0.5.jar
Decorative Blocks-forge-1.19.2-3.0.0.jar
Entity_Collision_FPS_Fix-forge-1.19-2.0.0.0.jar
Essential-forge_1-18-2.jar
FastFurnace-1.19.2-7.0.0.jar
Fastload-Reforged-2.6.9+1.19.2.jar
FastSuite-1.19.2-4.0.0.jar
ferritecore-5.0.3-forge.jar
flywheel-forge-1.19.2-0.6.8.a.jar
ftb-chunks-forge-1902.3.18-build.248.jar
ftb-library-forge-1902.3.15-build.188.jar
ftb-quests-forge-1902.4.9-build.195.jar
ftb-teams-forge-1902.2.12-build.95.jar
inventorio-1.19-forge-1.8.7.jar
item-filters-forge-1902.2.9-build.46.jar
ItShallNotTick-1.0.11-build.35.jar
Jade-1.19.1-forge-8.8.1.jar
JadeAddons-1.19.2-forge-3.4.0.jar
jei-1.19.2-forge-11.6.0.1013.jar
kotlinforforge-3.11.0-all.jar
modlist.txt
moonlight-1.19.2-2.2.23-forge.jar
Placebo-1.19.2-7.1.5.jar
radon-0.8.2.jar
sophisticatedbackpacks-1.19.2-3.18.40.779.jar
sophisticatedcore-1.19.2-0.5.38.203.jar
Steam_Rails-1.19.2-1.1.1.jar

### Additional Information

Don't have lithium. This world of mine is very new.
Am new to bug reports, so ask for some info if i forgot something :)

**Comment by AbdElAziz333** [comment]
can you please try the new update?

**Comment by AbdElAziz333** [comment]
Fixed in the new updates.

**Comment by Pedgux** [comment]
> Fixed in the new updates.

Sorry for responding so late, but yeah i can confirm. It works
