### ISSUE TITLE
Crash with Xaero's World Map when entering a world

### ISSUE THREAD

**Issue by Sovok1917** [AbdElAziz333/Canary#190]
### Version
> canary-mc1.20.1-0.2.7

### Reproduction Steps

>Game crashes when trying to enter any world with both mods installed

### Crash Report File
>[crash-2023-12-15_16.42.44-server.txt](https://github.com/AbdElAziz333/Canary/files/13685847/crash-2023-12-15_16.42.44-server.txt)

### Additional Information
>Removing any of the 2 mods stops the crashing from happening, leaving only them installed also crashes the game

**Comment by AbdElAziz333** [comment]
Fixed in the new updates.
