### ISSUE TITLE
Canary causes a Crash when near an Allay

### ISSUE THREAD

**Issue by LolJohn11** [AbdElAziz333/Canary#191]
### Version
Canary-mc1.19.2-0.2.8

### Reproduction Steps
In my case, I've encountered this crash when running around a pillager outpost. Looking at the crash report file, it seems that an allay has caused a crash.

### Crash Report File
https://gist.github.com/LolJohn11/6ec300eb59e98eaf072ad0657a1462f0

### Additional Information
The crash does not occur when Canary is disabled.
Disabling Canary and then enabling it again and loading up the same save seems to not cause the crash again.

**Comment by Nereithr** [comment]
I can't reproduce the crash on 1.19.2 with Canary alone, nor 90 other mods present. I see that you have Forgery (fabrication in the crash log) present as well and it has a bunch of mob ai related  stuff in it. Try disabling Forgery, if it works without Forgery, the issue likely lies on the intersection between one of the Forgery tweaks and Canary (aka you need to disable either the module or Canary).

**Comment by LolJohn11** [comment]
Thanks for the advice, I'll test this approach if I encounter a crash again.

**Comment by AbdElAziz333** [comment]
This issue is from Saturn mod, can you please try the new Saturn versions?

**Comment by LolJohn11** [comment]
> This issue is from Saturn mod, can you please try the new Saturn versions?

I've installed the new latest versions of both Canary and Saturn mods and will report if I encounter another crash like the ones I had previously.
