### ISSUE TITLE
[1.18.2] Crash with Ticking Entity: SetWalkTargetFromLookTarget (Hoglin)

### ISSUE THREAD

**Issue by Darkfiend009** [AbdElAziz333/Canary#192]
### Version
>canary-mc1.18.2-0.2.4
 
### Reproduction Steps

> While it is not easily replicated due to the nature of the crash, it did occur twice, one after the other. 
> Example:
> 1. Enter Nether
> 2. Go load chunk where the Hoglin is present
> 3. Crash

### Crash Report File

Crash Report: https://pastebin.com/qfwUJr9p

### Additional Information

The server has been running for almost 2 months now. This is the first time we've encountered the issue and it was back to back crashes for the same user. Makes me think it's pretty rare and definitely infrequent.

**Comment by PhweeDev** [comment]
Same issue there, this is getting pretty constant with me and my friend

**Comment by BoxWithoutATop** [comment]
Also on 1.19.2. Hoglin mob is causing issues while ticking. Happens once or twice every hour, so long as the nether is loaded. The issue doesn't persist with Canary removed. 

https://mclo.gs/2xXoJyu

**Comment by PhweeDev** [comment]
Here's the report for why it crashed.  In this case, it's a Villager being ticked.

https://paste.gg/p/anonymous/24903ca2aab441608e48a699cf05eca2

**Comment by AbdElAziz333** [comment]
This issue is from Saturn mod, can you please try the new Saturn versions?
