### ISSUE TITLE
World block are reset

### ISSUE THREAD

**Issue by zeid0ne** [AbdElAziz333/Canary#193]
### Version Information

canary-mc1.20.1-0.2.8.jar

### Expected Behavior

My world block are not reseted

### Actual Behavior

My inventory and my pets are still here, but the world blocks are the same at the world creation.

### Reproduction Steps

1) create a world with canary-mc1.20.1-0.2.7.jar
2) place and destroy some blocks
3) close minecraft
4) update canary to 0.2.8.jar
5) open the world again

**Comment by AbdElAziz333** [comment]
can you please try this [update](https://github.com/AbdElAziz333/Canary/releases/tag/mc1.20.1-0.2.9)?

**Comment by zeid0ne** [comment]
seems fixed, thanks !
