### ISSUE TITLE
Canary 0.2.9 for MC 1.19.2 - The entire world was regenerated, all the players' houses disappeared.

### ISSUE THREAD

**Issue by kitovoi111** [AbdElAziz333/Canary#194]
Canary 0.2.9 for MC 1.19.2 - The entire world was regenerated, all the players' houses disappeared. I installed this mod on my server and the entire map was regenerated in pieces.

**Comment by AbdElAziz333** [comment]
can you please try this [update](https://github.com/AbdElAziz333/Canary/releases/tag/mc1.19.2-0.2.10)?

**Comment by kitovoi111** [comment]
Fixed.

**Comment by EtSL33py** [comment]
Have same issue with Canary 0.2.9 for MC 1.20.1

**Comment by AbdElAziz333** [comment]
@EtSL33py can you try the new update from [here](https://github.com/AbdElAziz333/Canary/releases/tag/mc1.20.1-0.2.10) please?
