### ISSUE TITLE
Server crash Canary 0.2.9 + it destroyed a farm in my world (where I logged out prev. session)

### ISSUE THREAD

**Issue by Nycto97** [AbdElAziz333/Canary#195]
### Version

canary-mc1.19.2-0.2.9

### Reproduction Steps

1. Update Canary from 0.2.8 to 0.2.9
2. Launch server
3. Experience server crash
4. Downgrade back to 0.2.8
5. Launch server
6. Experience world destruction

### Config

I have `mixin.world.chunk_access=false` in `canary.properties`

### Server mods

Note: dumped list when 0.2.8 was installed

[mod-list_2023-12-24_12.51.18.txt](https://github.com/AbdElAziz333/Canary/files/13761667/mod-list_2023-12-24_12.51.18.txt)

### Crash Report File

[crash-2023-12-24_12.16.34-server.txt](https://github.com/AbdElAziz333/Canary/files/13761628/crash-2023-12-24_12.16.34-server.txt)

### World Destruction

Before:

![2023-12-24_12 41 10](https://github.com/AbdElAziz333/Canary/assets/83367226/14b4e9c8-f556-4219-9a75-6a7a0fb876da)

After:

![2023-12-24_12 31 40](https://github.com/AbdElAziz333/Canary/assets/83367226/3cba62a3-0316-4e8d-896b-ef1fc71f2bed)

**Comment by Nycto97** [comment]
Notice on the minimap, the boat also looks broken (didn't actually look at it in game)

**Comment by AbdElAziz333** [comment]
can you please try this [update](https://github.com/AbdElAziz333/Canary/releases/tag/mc1.18.2-0.2.6)?

**Comment by Nycto97** [comment]
It says MC 1.18.2, do I still test this on my 1.19.2?

**Comment by AbdElAziz333** [comment]
Sorry, press [here](https://github.com/AbdElAziz333/Canary/releases/tag/mc1.19.2-0.2.10) to get the 1.19.2 version.

**Comment by Nycto97** [comment]
I guess you meant to link the one you linked in the other Issue: https://github.com/AbdElAziz333/Canary/issues/194#issuecomment-1868520117

I'll try that one

**Comment by Nycto97** [comment]
[latest.log](https://github.com/AbdElAziz333/Canary/files/13761997/latest.log)

This doesn't show up in latest.log tho:

![image](https://github.com/AbdElAziz333/Canary/assets/83367226/55d3ca2f-7c98-4e8a-96ef-fa7d06ed0160)

Farm seems untouched:

![image](https://github.com/AbdElAziz333/Canary/assets/83367226/2008a595-800d-4e1a-95f9-2d58e20a2564)

**Comment by AbdElAziz333** [comment]
Yes, this text is from ModernFix mod disables a mixin that are from both Canary and ModernFix, but Canary disabled it by itself so the text no longer shows.
