### ISSUE TITLE
0.2.9 causes POI data mismatch / 1.20.1

### ISSUE THREAD

**Issue by ZenZenXDz** [AbdElAziz333/Canary#198]
### Version Information

> Canary-1.20.1-0.2.9

### Expected Behavior

> Recently placed blocks won't disappear in a dimension (ATM Dimension).

### Actual Behavior

> Blocks disappear
### Reproduction Steps

> Place blocks in ATM Dimension
> Warp out of Dimension
> Come back
> Blocks disappear
### Other Information

> Before (0.2.8) there's no issues, but after updating. I lost my build on a world, and now it disappeared my place blocks. Look at the map.
![2023-12-24_20 25 32](https://github.com/AbdElAziz333/Canary/assets/66781695/e5ac3a71-438e-4c1b-a5aa-073bcc3bd468) 

[latest.log](https://github.com/AbdElAziz333/Canary/files/13766028/latest.log)

**Comment by ZenZenXDz** [comment]
![Uploading 2023-12-24_20.25.32.png…]()

**Comment by ZenZenXDz** [comment]
![2023-12-24_20 25 32](https://github.com/AbdElAziz333/Canary/assets/66781695/1f1bf296-8ca0-4899-8beb-498e676645f1)

**Comment by ZenZenXDz** [comment]
Also, this was used in Pojav Launcher. And FYI the mod has caused the issue not the Launcher.

**Comment by AbdElAziz333** [comment]
can you try the new update from [here](https://github.com/AbdElAziz333/Canary/releases/tag/mc1.20.1-0.2.10) please?

**Comment by ZenZenXDz** [comment]
Fixed
