### ISSUE TITLE
[Mod Interaction] Hoppers don't restart after target inventory (from Easy Villagers) has more room for them to insert

### ISSUE THREAD

**Issue by zlainsama** [AbdElAziz333/Canary#199]
### Version Information

> canary-mc1.20.1-0.2.10
> easy_villagers-1.20.1-1.0.17

### Expected Behavior

> Hoppers start to insert after target inventory has more room.

### Actual Behavior

> Hopper fills an Incubator from Easy Villagers mod with Baby Villagers, stops, and doesn't restart inserting after said Incubator has more room.

### Reproduction Steps

> Grab a Hopper and an Incubator from Easy Villagers mod, and place them with Hopper facing Incubator.
> Fill the Hopper with Baby Villagers until both Hopper and Incubator full.
> Remove a Baby Villager through the Incubator's GUI.
> Observe the Hopper don't insert another Baby Villager.

### Other Information

> This issue also happens with other blocks in Easy Villagers mod, and with ordinary items (carrots, etc.).
> Updating the Hopper cause it to start inserting, and this issue happen again when target inventory is filled.
> In canary-mc1.20.1-0.2.7, this issue does not occur.
> Vanilla blocks don't have this issue.

**Comment by AbdElAziz333** [comment]
Please try the new update from [here](https://github.com/AbdElAziz333/Canary/releases/tag/mc1.20.1-0.3.0) for MC 1.20.1.

**Comment by zlainsama** [comment]
Confirmed, no longer occurs in canary-mc1.20.1-0.3.0.

**Comment by zlainsama** [comment]
However, there seems to be memory leaks, in like 15 minutes or so with canary-mc1.20.1-0.3.0, game starts to stutter due to memory constraints, reverting back to canary-mc1.20.1-0.2.10 fixed it.

**Comment by AbdElAziz333** [comment]
you can add `mixin.block.hopper=false` in `canary.properties` until i release a fix for this.

**Comment by AbdElAziz333** [comment]
Can you please try the latest update.

**Comment by zlainsama** [comment]
Seems the memory issue no longer occurs with canary-mc1.20.1-0.3.1.
