### ISSUE TITLE
Is 1.18 gonna get performance updates as well?

### ISSUE THREAD

**Issue by Pineappleguy03** [AbdElAziz333/Canary#2]
the title says it all.

**Comment by AbdElAziz333** [comment]
Sure.

**Comment by Pineappleguy03** [comment]
Appreciate it my dude. 1.18 Users are very common due to the amazing mod Create. So I thank you for also considering us.

**Comment by AbdElAziz333** [comment]
1.18.2 version is updated to 0.0.2 with the newer optimization and bug fixes.

Installation :

https://www.curseforge.com/minecraft/mc-mods/canary/files/3984103

Have Fun!
