### ISSUE TITLE
Hopper Update

### ISSUE THREAD

**Issue by Mont-Site** [AbdElAziz333/Canary#202]
• Version Information

> canary-mc1.18.2-0.2.4.jar

• Behavior

After a while, the pistons stop updating and no longer inject items into the block.
There's no need to change dimension, reload the chunk or reload the saveguard for the bug to occur.

• Reproduction Steps

Place a drawer filled with cobblestone on top of a modded block such as a generator or sieve.
Wait 10min to 30min => no more items enter the block (generator or sieve).

**Comment by AbdElAziz333** [comment]
Can you please post the mods list or an screenshot to the issue?
