### ISSUE TITLE
Clouds are black

### ISSUE THREAD

**Issue by VenusVesper** [AbdElAziz333/Canary#205]
#### Instructions

This is a template for the issue you are about to open! It will help you provide the information necessary
to complete your **bug report**. Before you open an issue, ensure you've completed every step on the checklist below.

- Have you used the search tool to find similar issues? Make sure you are not opening a duplicate.
- Are you using the latest version of the mod? If not, try updating to see if it resolves your issue.

All good? Please read through the sections below, and fill out any lines starting with an arrow. Then, remove
everything above this dashed line (including the line itself.)

------------------------

### Version Information

Forge- 43.3.5
MC- 1.19.2: 0.3.1

### Expected Behavior

I expected the clouds to be white color.

### Actual Behavior

Clouds were black, as if it was night or a thunder storm, but it was daytime.

### Reproduction Steps

All I did was load the game and the clouds were black, I tried loading the game without canary the clouds were back to normal. 
The clouds weren't black when I used shaders (shaders used: Super Duper Vanilla Shaders).

### Other Information

I'm using canary in a modpack of 289 mods.

**Comment by AbdElAziz333** [comment]
Can you please test with only Canary and see if the issue still happens?

**Comment by VenusVesper** [comment]
The bug just disappeared, I did delete some mods I didn’t want from the modpack if it helps

•Let’s do vinery
•Controlling
•Yungs better end island
