### ISSUE TITLE
Hopper stops feeding into create deployer

### ISSUE THREAD

**Issue by FireFox1324** [AbdElAziz333/Canary#207]
I'm using canary 1.19.2-0.3.1 on forge-43.3.5. When I have canary active it makes hoppers stop feeding into deployers when they get full. The hopper doesn't work again until you remove an item from it. I tested my other mods and the issue only happens with canary.

**Comment by JJellie** [comment]
This bug also occurs in 1.20.1-0.2.10. 
To be more specific about it's occurrence, it happens whenever a create block with an inventory is full. This stops the hopper from inputting into that block, however when the create block with an inventory is no longer full, the hopper does not restart pushing items into the block.

The blocks I've tested are the deployer, mechanical crafter and basin, they all display the same effect.

**Comment by AbdElAziz333** [comment]
Can you please test the new updates?

**Comment by JJellie** [comment]
Using the same setup as before, it now functions as expected, thus it should be fixed.
