### ISSUE TITLE
Entities with the LookAtEntityGoal don't look at entities they should be tracking

### ISSUE THREAD

**Issue by SmileycorpMC** [AbdElAziz333/Canary#21]
------------------------

### Version Information

canary-mc1.18.2-0.0.7

### Expected Behavior

Mobs using LookAtEntityGoal should track nearby entities of the right class and look at them.

### Actual Behavior

Mobs with the LookAtEntityGoal don't look at nearby entities of the right class.

### Reproduction Steps

1) Spawn a passive entity, which would normally look at nearby players e.g. Cow
2) The entity doesn't look at the player.

### Other Information

Tested with only canary installed, behavior works as expected without the mod installed.

**Comment by AbdElAziz333** [comment]
fixed in the new update, and if you want 1.18.2 maybe it will be released tomorrow, good luck!
