### ISSUE TITLE
Error on Startup with java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by CepheidVariable** [AbdElAziz333/Canary#22]
| Component              | Version |
|------------------------|---------|
| Minecraft              | 1.19.2  |
| Forge                  | 43.1.43 |
| Canary                 | 0.0.4   |
| Pluto                  | 0.0.3   |
| Saturn                 | 0.0.1   |
| Smooth Boot (Reforged) | 1.0.5   |
| Advancement Frames | 1.19.2-2.0.0 |

### Reproduction Steps
Start game to cause crash.

### Crash Report File
https://paste.ee/p/YLpNe

### Additional Information

Removing the Advancement Frames mod eliminates the crash.
Possible incompatibility?

**Comment by AbdElAziz333** [comment]
its not incompatibility, you are missing Moonlight which is required by Advancement Frames mod.

**Comment by CepheidVariable** [comment]
> its not incompatibility, you are missing Moonlight which is required by Advancement Frames mod.

Thank you for pointing that out. For some reason Moonlight isn't listed as a required dependency on the mod's download page;  I've added it, and as expected, error is now resolved.
