### ISSUE TITLE
[1.19.2] Crashes related to InventoryChangeTracker

### ISSUE THREAD

**Issue by originalusername32** [AbdElAziz333/Canary#26]
Forge ver.: forge-1.19.2-43.1.43
Mod ver.: canary-mc1.19.2-0.0.5

Reproduction Steps
Either a) explore world until crash when generating new chunk or b) generate new world until crash (both scenarios are in order respective to the crash reports below)

Crash Report Files
[crash-2022-10-20_15.28.20-server.txt](https://github.com/AbdElAziz333/Canary/files/9833846/crash-2022-10-20_15.28.20-server.txt)
[crash-2022-10-20_15.55.09-server.txt](https://github.com/AbdElAziz333/Canary/files/9833849/crash-2022-10-20_15.55.09-server.txt)

Edit: I think the problem may have something to do with Optifine but I'm unsure

**Comment by originalusername32** [comment]
When downgrading to version 0.0.4 of Canary I was unable to produce the crash again

**Comment by AbdElAziz333** [comment]
fixed in 0.0.6 update.

**Comment by Gbergz** [comment]
Still got it in 0.0.6 https://gist.github.com/Gbergz/908c4cfd33d560437cec30c5b00989ed

**Comment by vrork** [comment]
Present in 0.0.6, here is the log
[latest.log](https://github.com/AbdElAziz333/Canary/files/9835349/latest.log)

**Comment by Pentasis** [comment]
I too confirm it's there in 0.0.6: [Crashlog](https://pastebin.com/9gEvTtC7)

**Comment by AbdElAziz333** [comment]
should be fixed in 0.0.7.
