### ISSUE TITLE
[1.19.2 Forge] Startup Crash by Suspected incompatibility with Combat Roll(?)

### ISSUE THREAD

**Issue by RedBeast1959** [AbdElAziz333/Canary#27]
Forge 43.1.43
canary-mc1.19.2-0.0.6.jar
pluto-mc1.19.2-0.0.3.jar
smoothboot(reloaded)-mc1.19.2-1.0.5.jar
saturn-mc1.19.2-0.0.1.jar

combatroll-forge-1.0.8+1.19.jar
(https://www.curseforge.com/minecraft/mc-mods/combat-roll)

I'm not sure that it is really incompatibility with Combat Roll mod or other mods's problem. But crash report says combat roll mod crashed with current 1.19.2 version of canary. When I downgraded canary to 0.04 version, modpack crash problem solved.

[crash-2022-10-21_17.09.43-fml.txt](https://github.com/AbdElAziz333/Canary/files/9837117/crash-2022-10-21_17.09.43-fml.txt)
[latest.log](https://github.com/AbdElAziz333/Canary/files/9837118/latest.log)

**Comment by AbdElAziz333** [comment]
Are you sure this issue in not from Sound Physics mod?

**Comment by RedBeast1959** [comment]
During that crash, I just saw default minecraft mod loading fail screen and it said combat roll failed to load.

So... real problem is sound physics or cloth config mod?

**Comment by AbdElAziz333** [comment]
could you please test without sound physics mod ?

**Comment by RedBeast1959** [comment]
Hi, thanks to recent update of 0.07 version, crash problem fixed!
It now works with Soundphysic mod too! Thank you for making this mod!
