### ISSUE TITLE
Crash when block entity is destoried

### ISSUE THREAD

**Issue by Zelioth** [AbdElAziz333/Canary#28]
Hello again, Reported an error that you closed in version 0.0.5 that wouldn't allow either world creation or the launcher to launch. WELLLLLLLLL here we are again.

Updated to version 0.0.6
Last working Version 0.0.4
Minecraft 1.19.2
Forge 43.1.43

Mod Pack : Friends United 

https://crashy.net/MaGvAyvG5tfvM3mQCDzn

[crash-2022-10-21_21.08.14-client.txt](https://github.com/AbdElAziz333/Canary/files/9843371/crash-2022-10-21_21.08.14-client.txt)

**Comment by AbdElAziz333** [comment]
should be fixed in 0.0.7 update, I'm sorry!

**Comment by Zelioth** [comment]
It's alright I'm just teasing. Mod creating isn't the easiest and I'm sure you have a life outside of creating this mod. I have to be honest I'm not sure if it makes a difference being in the pack but I know removing it doesn't change anything either to my knowledge so well keep it in haha on 0.0.4 and keep testing 👯
