### ISSUE TITLE
[1.18.2] TPS is reported with good mspt, but in game the server is lagging more than when I used radium.

### ISSUE THREAD

**Issue by StormDragon-64** [AbdElAziz333/Canary#29]
When doing /forge tps or by using [server tab info](https://www.curseforge.com/minecraft/mc-mods/server-tab-info), the tps reports as 20 with a mspt of around 8-19 depending on how many people are playing and what they are doing. Even when the mspt reports as 8, it takes a few seconds just to open a chest or it takes extra long to eat food. Also, the performance of my server is way worse than when I used radium. My server is also only using 15% of its cpu even though its lagging behind, which wasn't a problem when I used radium. (server used 50% cpu with radium because that's all it needed, unless someone was loading chunks quickly.) While it is possible something else could be causing bad the performance, I am 99.9% sure the tps is reporting incorrectly.

**Comment by AbdElAziz333** [comment]
weird, i will look into this.

**Comment by StormDragon-64** [comment]
Yes, I have [my own modpack](https://www.curseforge.com/minecraft/modpacks/create-mod-plus), and the server is running it.

**Comment by StormDragon-64** [comment]
My server provider is [falixnodes](https://falixnodes.net/) (free plan) if you think the bad performance is a problem with them, (even though it worked fine when I used radium on the same server) but the tps reporting incorrectly probably isn't a problem with them.

**Comment by StormDragon-64** [comment]
Wait, I just realized. What if the reason why I am getting worse performance is because the server actually thinks it is performing fine when it isn't, so it doesn't use any of its resources? That would explain incorrect tps and bad performance

**Comment by StormDragon-64** [comment]
I just realized that I forgot to optimize the world (vanilla optimize world option) when I switched from radium to Canary. After doing that, the tps output is correct and the server performs similarly to when using radium. Maybe some old radium data was somehow messing it up?

**Comment by StormDragon-64** [comment]
One thing to note, I don't think it was actually because of the switch from radium to canary, I just didn't know at the time that ping could have the same effect as bad tps. I thought that ping = rubberbanding and delayed+continuous inputs, and I didn't know that it could have the same effects as low tps/high mspt as well (takes longer to eat food and open inventories, ect.)

**Comment by StormDragon-64** [comment]
Not saying you shouldn't optimize your world though, probably still a good idea
