### ISSUE TITLE
[1.18.2] Crash on world loading / chunk loading

### ISSUE THREAD

**Issue by tharrmeehan** [AbdElAziz333/Canary#3]
### Version

canary-mc1.18.2-0.0.2
on Forge 40.1.80 (latest)

### Reproduction Steps

1. Create a new world
2. Wait till it loads
3. Either it crashes directly or if you join the world and fly around it crashes

### Crash Report File

[crash-2022-09-11_21.52.30-server.txt](https://github.com/AbdElAziz333/Canary/files/9543409/crash-2022-09-11_21.52.30-server.txt)

### Minecraft Save

[New World.zip](https://github.com/AbdElAziz333/Canary/files/9543411/New.World.zip)

Not sure if this is needed. Probably not as it happens with every world. Might be an incompatibility issue with Dungeon Crawl. (https://www.curseforge.com/minecraft/mc-mods/dungeon-crawl)

### Additional Information

Crash does not happen with the 0.0.1 version, can confirm with a modpack running 288 mods.

**Comment by Pineappleguy03** [comment]
Also getting it.

**Comment by AbdElAziz333** [comment]
could you test the new version if the issue still exists?
https://www.curseforge.com/minecraft/mc-mods/canary/files/3984876

**Comment by tharrmeehan** [comment]
> could you test the new version if the issue still exists? https://www.curseforge.com/minecraft/mc-mods/canary/files/3984876

Seems to be working fine for me after testing for a bit. Thanks alot!

**Comment by tharrmeehan** [comment]
Hello, after testing it seems that my chunks get corrupted and reset. There are no crashes, but many errors. This does not happen with 0.0.1.
[2022-09-12-1.log.gz](https://github.com/AbdElAziz333/Canary/files/9548071/2022-09-12-1.log.gz)

**Comment by aking4125** [comment]
Can confirm the above issue. It fails to load chunks on existing worlds and spams the log with errors and generates new chunks on top of the old ones in real time. Causing the server to time out over and over again.

**Comment by Phweeeee** [comment]
> Hello, after testing it seems that my chunks get corrupted and reset. There are no crashes, but many errors. This does not happen with 0.0.1. [2022-09-12-1.log.gz](https://github.com/AbdElAziz333/Canary/files/9548071/2022-09-12-1.log.gz)

This happens with me as well.

**Comment by Pineappleguy03** [comment]
I lost my whole house due to this chunk corruption,

**Comment by Alucard1313** [comment]
> Hello, after testing it seems that my chunks get corrupted and reset. There are no crashes, but many errors. This does not happen with 0.0.1. [2022-09-12-1.log.gz](https://github.com/AbdElAziz333/Canary/files/9548071/2022-09-12-1.log.gz)

Same here

**Comment by AbdElAziz333** [comment]
I will look into this when i back to the home.

**Comment by AbdElAziz333** [comment]
Fixed in 0.0.4 version, with stable optimizations.
