### ISSUE TITLE
Hopper didn't work with composter when using Canary

### ISSUE THREAD

**Issue by Samapoke** [AbdElAziz333/Canary#30]
Version Information

canary-mc1.19.2-0.0.8

Expected Behavior

The seed should have entered the composter by going through a hopper

Actual Behavior

The hopper can't make the seeds entered the composter

 Reproduction Steps

1. Add seeds to the hopper which connected to the composter
3. Nothing happened

 Other Information
 I run a server
Server's Mod list:
- AI-Improvements-1.19.2-0.5.2
- AttributeFix-Forge-1.19.2-17.1.2
- canary-mc1.19.2-0.0.8
- Clumps-forge-1.19.2-9.0.0+11
- deuf-1.19.2-1.3
- EasierSleeping-1.19.2-2.1.2
- FastFurnace-1.19.2-7.0.0
- FastSuite-1.19.2-4.0.0
- FastWorkbench-1.19.2-7.0.1
- morevillagers-forge-1.19-4.0.3
- Placebo-1.19.2-7.0.1
- pluto-mc1.19.2-0.0.3
- saturn-mc1.19.2-0.0.1
- SereneSeasons-1.19-8.0.0.19

And me and my friends use Optifine.

**Comment by AbdElAziz333** [comment]
This is not a bug from Canary, this is a regular feature of vanilla.
for more information press [here](https://github.com/AbdElAziz333/Canary/blob/mc1.19.2/architectury_forge_loom/src/main/java/com/abdelaziz/canary/mixin/block/hopper/README.md#how-canary-hoppers-work-different-from-vanilla).

**Comment by AbdElAziz333** [comment]
Good luck!

**Comment by Samapoke** [comment]
> This is not a bug from Canary, this is a regular feature in Canary. for more information press [here](https://github.com/AbdElAziz333/Canary/blob/mc1.19.2/architectury_forge_loom/src/main/java/com/abdelaziz/canary/mixin/block/hopper/README.md#how-canary-hoppers-work-different-from-vanilla).

I see, how can I disable this function?

**Comment by AbdElAziz333** [comment]
add this line to canary.properties in the config file.
`mixin.block.hopper=false`

**Comment by Samapoke** [comment]
> add this line to canary.properties in the config file. `mixin.block.hopper=false`

Thank you!
