### ISSUE TITLE
[1.18.2] Getting game crash on startup

### ISSUE THREAD

**Issue by Chaos02** [AbdElAziz333/Canary#31]
### Version
canary-mc1.18.2-0.0.9

### Reproduction Steps
Try start game with my WIP modpack. 

### Crash Report File
[This](https://hastebin.com/uxeminegir.properties) is as much of the GameLog window I can capture for some reason.
It is not shown in any of latest.log or debug.log. debug.log is too large for pastebin.

### Additional Information
I am a seasoned modpack developer and have no idea what's causing this crash.

**Comment by AbdElAziz333** [comment]
duplicate issue of #14, take a look at the last comment at #14.
Good luck!
