### ISSUE TITLE
[1.19.2-Server] Exception generating new chunk

### ISSUE THREAD

**Issue by Gbergz** [AbdElAziz333/Canary#32]
### Version
>
> canary-mc1.19.2-0.0.7
forge 43.1.47
> 
### Reproduction Steps
>
> Example:
> 1. Generate chunk
> 2. Freeze.
> 3. Crash.

### Crash Report File

> https://gist.github.com/Gbergz/f0a85c94e0037ba41f290d355ed95d1c

### Minecraft Save

It's too large in gb's.

### Additional Information

> Just about it.

**Comment by AbdElAziz333** [comment]
could you please try with only Canary and Forge ?

**Comment by Gbergz** [comment]
Not sure it's reproducable as I've tried now. Seems to be random anyways.

**Comment by Gbergz** [comment]
But adding this line below to the Canary Config seems to have fixed it.
`mixin.entity.collisions=false`

**Comment by AbdElAziz333** [comment]
I will try to debug that.

**Comment by Gbergz** [comment]
Alright.

Also to add onto this, might be another issue but another crash: https://gist.github.com/Gbergz/f35b34ce0afd14dfad11a9c2a6cb7887

**Comment by AbdElAziz333** [comment]
Thanks for this log! i will fix this issue in the coming update.

**Comment by AbdElAziz333** [comment]
You are using 0.0.7, please try the latest version 0.0.9.
