### ISSUE TITLE
[Bug] Running Canary with Terrablender on 1.19.2 causes absurdly slow chunk loading speeds

### ISSUE THREAD

**Issue by DarthCaesium** [AbdElAziz333/Canary#33]
As the title says, something about the chunk and world generation optimisations not only doesn't seem to work with Terrablender, but it actually makes it slower than if Canary wasn't used. This seems to only be happening to me in 1.19.2, as I actually had the same issue in 1.18.2, but I fixed it by using this mod instead of Radium Reforged. I don't know if this performance regression has something to do with Lithium pushing something upstream, but there is an issue at present.

**Comment by AbdElAziz333** [comment]
Does it happens with **only** Canary and Terrablender or with other mods? if so i need more some info mods list, logs, does it happens in the 1.18 version or only 1.19?

**Comment by DarthCaesium** [comment]
When paired up with Terrablender, Rubidium does slow it down slightly in some situations (and speeds it up in others) but Canary really slows it down to the point where it's slower to use Canary with Terrablender than just using Terrablender. I'll give a mod list probably in several hours' time when I can access my computer. Just to note, this issue is only happening to me in 1.19.2, Canary in 1.18.2 in fact fixed the bug.

**Comment by AbdElAziz333** [comment]
fixed in 0.0.10.
