### ISSUE TITLE
1.19.2 Issues With Pokecube (Dev Requested I make this so you can communicate)

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [AbdElAziz333/Canary#34]
### Version Information

Forge Version 43.1.47

canary-mc1.19.2-0.0.9

pokecube-aio-1.19.2-3.19.2

### Expected Behavior

I should be able to use both mods together.

### Actual Behavior

When using both mods pokecube has random issues and it seems like canary acts differently too.

### Reproduction Steps

NA

### Other Information

Tagging Pokecube Dev @Thutmose He will work with you to make his mod and your mod play nice.

**Comment by AbdElAziz333** [comment]
i will look into that.

**Comment by AbdElAziz333** [comment]
what is the issues between both Canary and Pokemon?

**Comment by P3rf3ctXZer0** [comment]
Let me run some more tests and I will re-open this if things are still an issue.
