### ISSUE TITLE
[Crash / 1.19.2] Just a random crash happened in world.

### ISSUE THREAD

**Issue by murao-kun** [AbdElAziz333/Canary#36]
### Version

canary-mc1.19.2-0.0.9

### Crash Report File

[crash-2022-11-03_01.09.02-server.txt](https://github.com/AbdElAziz333/Canary/files/9924484/crash-2022-11-03_01.09.02-server.txt)

**Comment by murao-kun** [comment]
![image](https://user-images.githubusercontent.com/110398598/199613943-10a68b25-8307-4bdd-b262-b9c191f1f12d.png)
My config

**Comment by AbdElAziz333** [comment]
fixed in 0.0.10.
