### ISSUE TITLE
Problem with placebo

### ISSUE THREAD

**Issue by TathanDev** [AbdElAziz333/Canary#38]
### Version
canary-mc1.19.2-0.0.9.jar
### Reproduction Steps
Create a server with this modpack : https://www.curseforge.com/minecraft/modpacks/odysseyus-adventure-and-exploration
Add placebo
### Crash Report File

https://gist.github.com/TathanDev/45127c86e87eea18619ff3db6ac12da7
### Additional Information
I run my server with this modpack : https://www.curseforge.com/minecraft/modpacks/odysseyus-adventure-and-exploration

**Comment by AbdElAziz333** [comment]
duplicate issue of #14, you are missing a mod dependency or you should update forge, remove Canary from the mods folder and start the game like the regular and it will tell you the missed mod, after that re-add Canary again.

Good Luck!

**Comment by TathanDev** [comment]
Thanks
