### ISSUE TITLE
Canary Crash on ATM To The Sky 

### ISSUE THREAD

**Issue by Nuclearsmilz** [AbdElAziz333/Canary#39]
canary-mc1.18.2-0.0.9
forge-40.1.84
windows 11 pro
curseforge launcher

I added some mods to the pack (ATM To the Sky)

After adding all (I usually test each one but I was just quickly trying to get it working, will attach list of mods i added.
![mods added](https://user-images.githubusercontent.com/2687328/200200345-14d0732d-60d8-4db1-9d8a-dcb50a73a993.png) 
Canary is not in that list because i already removed it due to experiencing the crash.

Similar to another issue, I also experienced a canary crash on this version (canary-mc1.18.2-0.0.9) and forge (forge-40.1.84). I will try and reproduce the crash but it was related to mixins. Will update this post with crash log. Couldn't launch the game at all, not even a screen popped up.

EDIT: here is the launcher crash. Sorry it took a while, i had issues exporting/copying the log.
https://hastebin.com/xoguxecefe.yaml

**Comment by AbdElAziz333** [comment]
you have radium, which is OUT-DATED port of lithium, please remove radium and add canary and test again.

**Comment by Nuclearsmilz** [comment]
okay! will try now

**Comment by Nuclearsmilz** [comment]
oh. duh of course that would work. thank you very much. Appreciated.

**Comment by Nuclearsmilz** [comment]
It did work and launch. Thank you very much.

**Comment by Nuclearsmilz** [comment]
It did work and launch. Thank you very much.
