### ISSUE TITLE
Crash when even booting world.

### ISSUE THREAD

**Issue by Pineappleguy03** [AbdElAziz333/Canary#4]
Crashes right as it boots up

**Comment by Pineappleguy03** [comment]
[crash-2022-09-11_20.33.49-server.txt](https://github.com/AbdElAziz333/Canary/files/9543505/crash-2022-09-11_20.33.49-server.txt)

**Comment by Alucard1313** [comment]
Same here

**Comment by alexhowell610** [comment]
I'm getting this exact error. Good to know I'm not the only one.

**Comment by AbdElAziz333** [comment]
duplicate of #3, could you test the new version ?
https://www.curseforge.com/minecraft/mc-mods/canary/files/3984876

**Comment by Pineappleguy03** [comment]
Doesn't crash. Now it's just the chunk edit over.
