### ISSUE TITLE
1.19.2 - Crash Server Side Info (Not going to test things. Out of respect this might be valid. Seems like client protocol is trying to execute on server illegally.)

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [AbdElAziz333/Canary#40]
Forge: 43.1.47
Canary: canary-mc1.19.2-0.0.10

Latest.log
https://gist.github.com/P3rf3ctXZer0/e887f8637d8201e1be0f3c082ab3e402

This never happened with 

canary-mc1.19.2-0.0.9

**Comment by LaserLag** [comment]
Crash happening to me on Forge Server 43.1.47 with canary-mc1.19.2-0.0.10.jar as well. Same error.

**Comment by AbdElAziz333** [comment]
can you please test this [build](https://github.com/AbdElAziz333/Canary/releases/tag/mc1.19.2-v0.1.0-BETA)?

**Comment by AbdElAziz333** [comment]
fixed in the coming version.
