### ISSUE TITLE
[1.19.2 / 0.0.10] Crash on client start up.

### ISSUE THREAD

**Issue by murao-kun** [AbdElAziz333/Canary#42]
Crash on client start up. (No crash file generated)

### Version

canary-mc1.19.2-0.0.10

### Crash Report File

[debug.log](https://github.com/AbdElAziz333/Canary/files/9971653/debug.log)
[latest.log](https://github.com/AbdElAziz333/Canary/files/9971654/latest.log)

**Comment by murao-kun** [comment]
Compiled 0.1.0 by myself but it is still crashing.

[latest.log](https://github.com/AbdElAziz333/Canary/files/9991469/latest.log)
[debug.log](https://github.com/AbdElAziz333/Canary/files/9991468/debug.log)

**Comment by AbdElAziz333** [comment]
can you please test this [build](https://github.com/AbdElAziz333/Canary/releases/tag/mc1.19.2-v0.1.0-BETA)?

**Comment by murao-kun** [comment]
That is working now, thanks!

**Comment by AbdElAziz333** [comment]
fixed in the coming version.
