### ISSUE TITLE
[1.18.2] Moving hopper with a piston causes a crash (Quark "Pistons Move Tile Entities" feature)

### ISSUE THREAD

**Issue by Flyte-less** [AbdElAziz333/Canary#44]
### Version

canarymc1.18.2-0.0.9

### Reproduction Steps

Install quark (3.2-358) and AutoRegLib (Required for quark, 1.7-53). Load a new world, place down a hopper, place a sticky or normal piston facing into it, and give the piston power. Crashes when pushed.

### Crash Report File

https://mclo.gs/dFC5s5Y

### Minecraft Save

N/A

### Additional Information

Crash does not occur with only quark installed.

**Comment by AbdElAziz333** [comment]
can you test the latest update?, if the issue fixed in the new update please close the issue.
