### ISSUE TITLE
1.19.2 Crash on Ticking Block Entity

### ISSUE THREAD

**Issue by originalusername32** [AbdElAziz333/Canary#45]
Version
canary-mc1.19.2-0.0.10

Reproduction Steps
1. Place hopper on top of furnace
2. Put items into hopper
3. Hopper deposits one item into furnace
4. Crash

Crash report attached
[crash-2022-11-10_15.31.48-server.txt](https://github.com/AbdElAziz333/Canary/files/9984759/crash-2022-11-10_15.31.48-server.txt)

**Comment by originalusername32** [comment]
Going back in game, the hopper is filling the furnace without any problems. Have yet to crash again

**Comment by originalusername32** [comment]
Just encountered the same crash again
[crash-2022-11-10_16.08.48-server.txt](https://github.com/AbdElAziz333/Canary/files/9984951/crash-2022-11-10_16.08.48-server.txt)

**Comment by BugmanBugman** [comment]
https://bytebin.lucko.me/KaELKaYsUJ
Getting this issue as well

**Comment by AbdElAziz333** [comment]
fixed in the coming update.

**Comment by AbdElAziz333** [comment]
fixed in the coming version.
