### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Atlantispy** [AbdElAziz333/Canary#5]
#### Instructions

This is a template for the issue you are about to open! It will help you provide the information necessary
to complete your **crash report**. Before you open an issue, ensure you've completed every step on the checklist below.

- Have you used the search tool to find similar issues? Make sure you are not opening a duplicate.
- Are you using the latest version of the mod? If not, try updating to see if it resolves your issue.

All good? Please read through the sections below, and fill out any lines starting with an arrow. Then, remove
everything above this dashed line (including the line itself.)

------------------------

### Version

Canary-mc1.18.2-0.0.3

### Reproduction Steps

> Provide information on how to reproduce this game crash. You can either fill this section in like the example below
> or do something else -- just make sure your instructions are minimal and clear, as other people will need to be able
> to replicate your issue.
>
> Example:
> 1. Launch game
> 2. Walk around world
> 3. Crash happens

### Crash Report File

[crash-2022-09-12_11.05.37-server.txt](https://github.com/AbdElAziz333/Canary/files/9546990/crash-2022-09-12_11.05.37-server.txt)

**Comment by AbdElAziz333** [comment]
Fixed in 0.0.4 version.
