### ISSUE TITLE
Phasing as a phantom using Origins, causes damage

### ISSUE THREAD

**Issue by ArcusMG** [AbdElAziz333/Canary#50]
### Version Information

canary-mc1.19.2-0.0.7

### Expected Behavior

Expected to to be able to move into solid blocks with the phantom origin, without taking damage (though you should lose some hunger).

### Actual Behavior

when moving into a solid block, started taking suffocation damage.

### Reproduction Steps

1. load these mods:
canary
forge loader
origins for forge
and origin's library caelus
2. select the phantom origin when loading a world for the first time
3. attempt to move into a solid block
4. start suffocating

### Other Information

Not sure if this is an issue on the Origins mod end or Canary. I've reported it to both. Other mods installed:
forge 43.1.47
origins-forge-1.19.2-1.5.0.6-all
caelus-forge-1.19.2-3.0.0.6

**Comment by praus1** [comment]
A link to the bug report for the Origins mod:
https://github.com/EdwinMindcraft/origins-architectury/issues/273

**Comment by AbdElAziz333** [comment]
for now, you can add this line `mixin.entity.collisions.suffocation=false` in the config file canary.properties.

**Comment by BeckPhillips** [comment]
I tried changing the config file to include `mixin.entity.collisions.suffocation=false` but it didn't work. Any other ideas on what to do?

**Comment by AbdElAziz333** [comment]
can you please try the new update?

**Comment by BeckPhillips** [comment]
on which version?

**Comment by AbdElAziz333** [comment]
The version that you got the issue in it, press the versions below to get it faster.
[1.20.1](https://github.com/AbdElAziz333/Canary/releases/tag/mc1.20.1-0.2.10) - [1.19.2](https://github.com/AbdElAziz333/Canary/releases/tag/mc1.19.2-0.2.10) - [1.18.2](https://github.com/AbdElAziz333/Canary/releases/tag/mc1.18.2-0.2.6)

**Comment by BeckPhillips** [comment]
sorry about taking so long to reply, I've not been free to test it out - but using the latest Modrinth version of Origins and Canary results in taking suffocation damage still.

**Comment by mosharky** [comment]
i made a kubejs server script to fix this:
```js
ServerEvents.highPriorityData(e => {
    e.addJson('kubejs:powers/phantom/suffocation_fix.json', {
        hidden: true,
        type: 'origins:multiple',
        inwall: {
            type: 'origins:invulnerability',
            damage_condition: {
                type: 'origins:name',
                name: 'inWall'
            }
        },
        inwall_2: {
            type: 'origins:invulnerability',
            damage_condition: {
                type: 'origins:name',
                name: 'inWall.player'
            }
        }
    })

    e.addJson('origins:origins/phantom.json', {
        loading_priority: 10,
        powers: [
            'origins:phantomize',
            'origins:translucent',
            'origins:phasing',
            'origins:invisibility',
            'origins:burn_in_daylight',
            'origins:hunger_over_time',
            'origins:fragile',
            'origins:phantomize_overlay',
            'kubejs:phantom/suffocation_fix'
        ],
        icon: { item: 'minecraft:phantom_membrane' },
        order: 2,
        impact: 3
    })
})
```
it can absolutely be a datapack but im lazy and this issue's closed anyway
