### ISSUE TITLE
[1.18.2]Exception ticking world

### ISSUE THREAD

**Issue by OcrSu** [AbdElAziz333/Canary#53]
[游戏崩溃前的输出.txt](https://github.com/AbdElAziz333/Canary/files/10026420/default.txt)

[crash-2022-11-17_07.18.03-server.txt](https://github.com/AbdElAziz333/Canary/files/10026418/crash-2022-11-17_07.18.03-server.txt)

canary-mc1.18.2-0.0.10.jar
Java17
Win10 x64
First of all, I need to express my apology.

I have not found any clear suspect mod, and there is no evidence that it is caused by your module.

Because I don't have the ability to find the source of the bug, I don't understand the machine language java at all.

I'd like to ask you to help me find out what the problem is. If it bothers you, you can directly close the issue

**Comment by OcrSu** [comment]
> 没有金丝雀会发生这种情况吗？从日志中，我了解到，当 WYML（为什么你制作滞后）mod 开始清理块生成管理器的缓存时，您的游戏已经崩溃，所以也许 WYML 是错误的 mod。

The probability of this crash is extremely low. Thank you for the clues. I will try to delete WYML and observe it. When it is confirmed that it is his problem, I will leave a message here.

**Comment by AbdElAziz333** [comment]
Take your time! Good Luck!

**Comment by OcrSu** [comment]
It seems that the problem has disappeared. The crash may be an accident
