### ISSUE TITLE
Crash on attempted run (all version after canary-mc1.19.2-0.0.9.jar)

### ISSUE THREAD

**Issue by pat277** [AbdElAziz333/Canary#56]
### Reproduction Steps
> Attempt to run the game
### Crash Report File
[debug.log](https://github.com/AbdElAziz333/Canary/files/10035583/debug.log)

**Comment by AbdElAziz333** [comment]
This issue should be fixed in this new [build](https://github.com/AbdElAziz333/Canary/releases/tag/mc1.19.2-v0.1.3-R)

I hope you have a good day!

**Comment by pat277** [comment]
> This issue should be fixed in this new [build](https://github.com/AbdElAziz333/Canary/releases/tag/mc1.19.2-v0.1.3-R)
> 
> I hope you have a good day!
