### ISSUE TITLE
Shulker Boxes don't close properly

### ISSUE THREAD

**Issue by AtomicHaggis** [AbdElAziz333/Canary#57]
### Version Information

Canary 1.19.2-0.1.2

### Expected Behavior

Shulker boxes open and close normally.

### Actual Behavior

Shulker boxes open without problems, but when closing the animation gets stuck between the last few frames and never fully closes.  It doesn't appear to affect the functionality of the shulker box in any way, however.

### Reproduction Steps

1.  Place a shulker box from your inventory and open it, or open an existing placed shulker.
2.  Close the shulker box inventory
3.  Watch as the shulker box animation flickers back and forth

Reloading the chunk or restarting the game fixes the problem.

### Other Information

I have attached a GIF of the problem in action.

I am using the following mods along with Canary:

alexsmobs-1.21.0
Aquaculture-1.19.2-2.4.8
architectury-6.3.49-forge
citadel-2.0.0-1.19
Dynmap-3.4-forge-1.19.2
EditSign-1.19.2-2.6.0
exoticbirds-1.19.2-2.6.0
ftb-chunks-forge-1902.3.9-build.168
ftb-essentials-1902.1.10-build.47
FTB-Library-Mod-Forge-1.19.2
ftb-ranks-forge-1902.1.11-build.46
ftb-teams-forge-1902.2.9-build.61
NoChatReports-FORGE-1.19.2-v1.5.1

**Comment by AtomicHaggis** [comment]
https://user-images.githubusercontent.com/97291028/202695311-b88c5d4a-df18-4dbc-8c56-c18c28ab622b.mp4

**Comment by AbdElAziz333** [comment]
This is a known issue, for now you can add `mixin.world.block_entity_ticking.sleeping.shulker_box=false` until i fix it.

**Comment by AtomicHaggis** [comment]
Okay. I've added this into canary.properties and I will restart my server when all players log off to test.

**Comment by AbdElAziz333** [comment]
This issue is fixed in this [update](https://www.curseforge.com/minecraft/mc-mods/canary/files/4260201).
I hope you have a good day!
