### ISSUE TITLE
[Issue] Chunks still load slower in 1.19.2 using Canary 0.1.3 and the latest version of Terrablender compared to 1.18.2

### ISSUE THREAD

**Issue by DarthCaesium** [AbdElAziz333/Canary#59]
The chunk performance has massively improved since 0.0.10 added the chunk optimisation flags, and the latest versions have further improved it, but it is still not fast enough to fly around in creative or to fly with an elytra without hitting unloaded chunks. I'm not sure whether it's partially to do with 1.19.2 being even more of an unoptimised mess than 1.18.2, me being unable to determine how much memory to use when using FerriteCore, or if it's something else, but nonetheless chunk loading still isn't fast enough when used with Terrablender in 1.19.2. In a superflat world, which isn't managed by Terrablender, I get amazingly seemless chunk loading speeds, but in a regular world, Terrablender issues cause painful chunk loading speeds.

**Comment by Gbergz** [comment]
Can confirm.

**Comment by AbdElAziz333** [comment]
can you please use the new update?
[1.19.4](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4498538) - [1.19.3](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4498537) - [1.19.2](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4498536) - [1.18.2](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4498539)

**Comment by DarthCaesium** [comment]
Actually, never mind that, as there is still an issue with tps, although it's less common and less of a problem. There is also microstutter at times due to it, but it seems to generally be a microstutter with tps rather than fps, as my fps only drops by at most 20fps when it happens. My monitor is 144Hz if that helps.

**Comment by AbdElAziz333** [comment]
can you please try the new update?

**Comment by DarthCaesium** [comment]
Tried, no difference. Also can confirm the same happens in 1.20.1.
