### ISSUE TITLE
Canary breaks energy system in my world

### ISSUE THREAD

**Issue by Nakura29** [AbdElAziz333/Canary#6]
Version Information

> canary-mc1.18.2-0.0.3.jar
> canary-mc1.18.2-0.0.2.jar

latest version of Canary breaks energy system in my world. machinery stopped working, generators not generating energy etc.
tried downgrading to version 1.18.2-0.0.2 but the issue is persistent. reverting back to version 1.18.2-0.0.1 fixed this issue

step to reproduce
1. install canary version 1.18.2-0.0.3 or 1.18.2-0.0.2
2. install energy based mods (thermal, mekanism)
3. try generating or transporting energy

**Comment by AbdElAziz333** [comment]
Fixed in 0.0.4 version.
