### ISSUE TITLE
[1.18.2] BUG & CRASH | Enigmatica 8 Server

### ISSUE THREAD

**Issue by X-Niter** [AbdElAziz333/Canary#62]
### Version
`canary-mc1.18.2-0.0.10`

### Reproduction Steps

- Upload Canary to E8 Server.
- Login
- Wait, then crash and or if lucky only get kicked.

Adding `mixin.ai.nearby_entity_tracking=false` allows us to login farther but then get kicked instead of crashing.

### Crash Report File

[Server Latest log](https://gist.github.com/X-Niter/06c3d5a1c58875bd7c5d8f1f4882260d)
[Client Crash Report](https://gist.github.com/X-Niter/176deaf55ac8206bfb68cbb9428d41c9)
[Server Debug Log](https://gist.github.com/X-Niter/5a289f2ffd2a04f2c4339e2e8fdc386c)

### Additional Information

The mod being removed takes the issue away.
Clients do not have Canary in.
Client with Canary in still fails the same.

**Comment by AbdElAziz333** [comment]
i will look into that.

**Comment by AbdElAziz333** [comment]
Can you try this [update](https://www.curseforge.com/minecraft/mc-mods/canary/files/4260286)?

**Comment by AbdElAziz333** [comment]
should be fixed in the new updates.
[1.19.3](https://www.curseforge.com/minecraft/mc-mods/canary/files/4291690) - [1.19.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4291688) - [1.18.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4291687) .
Good luck!
