### ISSUE TITLE
Canary Mixins Found during multiple crashing events

### ISSUE THREAD

**Issue by Zelioth** [AbdElAziz333/Canary#64]
------------------------

### Version Information

Canary-mc1.19.2-0.1.3.ajr

### Expected Behavior

To not cause crashing events on a public server environment with one player online 

### Actual Behavior
The server sometimes crashes to which the crash logs indicate that Canary Mixins are found during the crashing events. 

### Reproduction Steps
I'm not even sure how to answer this. We have tons of mods and things going on but since Not_Enough_Crashes and BOLT it tells what Mixins were present during the crash for better understanding. 

[crash-2022-11-23_20.35.21-server.txt](https://github.com/AbdElAziz333/Canary/files/10080504/crash-2022-11-23_20.35.21-server.txt)

**Comment by AbdElAziz333** [comment]
Try one of those updates, if this issue still happens, please open a new issue.
[1.19.3](https://www.curseforge.com/minecraft/mc-mods/canary/files/4291690) - [1.19.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4291688) - [1.18.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4291687) .
Good luck!
