### ISSUE TITLE
Shaders support

### ISSUE THREAD

**Issue by michael554466** [AbdElAziz333/Canary#65]
**Is your feature request related to a problem? Please describe.**
I would like to use shaders with this mod, but when I install 'iris-mc1.19.2-1.4.2', unlike the fabric version, the shaders tab doesn't appear in the graphics settings.

**Describe the solution you'd like**
Add the feature from the fabric version,  adding a shaders tab to the graphics settings plz.

**Describe alternatives you've considered**
I''ve tried optifine(what I was using before), but that doesn't work either :(

**Additional context**
This will be great for even higher end systems that want to get the most fps alongside their crazy resourcepacks, mods and shaders.
It also allows lower end pcs to run some lite shaders while benifiting from all the performance boosting this suite of mods delivers.

Thank you for your time and for creating such great mods!

**Comment by michael554466** [comment]
Ah, my bad - seems like Iris shaders is fabric only. would still love a shaders issue plz tho.

**Comment by AbdElAziz333** [comment]
I think you have come to the wrong repository. This is Canary mod repository which is unofficial fork of Lithium for **Minecraft Forge**.
