### ISSUE TITLE
server crash: Attempted to load class com/mojang/blaze3d/vertex/PoseStack

### ISSUE THREAD

**Issue by VinceKezel** [AbdElAziz333/Canary#66]
### Version (for example 1, see 2022-12-05-2.log)
canary-mc1.19.20.0.3
Forge 43.1.52

### Version (for example 2, see 2022-12-05-3.log)
canary-mc1.19.2-0.1.3
Forge 43.1.65

### Reproduction Steps
Example 1: Start local multiplayer server. Generate chunk with small ship entity. Server crashes. See 2022-12-05-2.log linked.
Example 2: Start local multiplayer server. Join. Server crashes. See 2022-12-05-3.log linked.

### Crash Report File
example 1: [2022-12-05-2.log](https://gist.github.com/VinceKezel/3e142b985168b465c75a8331f5e56717)
example 2: [2022-12-05-3.log](https://gist.github.com/VinceKezel/f3399f391b3b8fe269c9de86a9c7e9aa)

### Additional Information

Forge 43.1.1 + canary-mc1.19.20.0.3  and the same mods did not produce any crashes.
Updating FML started the issue, but was required for some other mods.

Guessing is has something to do with 
`Attempted to load class com/mojang/blaze3d/vertex/PoseStack`

Lithium is not installed.

There was another instance where generating a chunck with an ocean monument threw a similar PostStack error from canary.

I am willing to add/remove mods and try different versions of FML or canary to provide more logs if needed.

Installed mods:

> additionallanterns-1.0.1a-forge-mc1.19.jar
> Adorn-3.6.1+1.19-forge.jar
> AI-Improvements-1.19.2-0.5.2.jar
> alexsmobs-1.21.0.jar
> Animal+Tamer+1.11.3+-1.19.jar
> another_furniture-forge-2.0.3-1.19.2.jar
> architectury-6.2.46-forge.jar
> AutoRegLib-1.8-54.jar
> balm-4.5.3.jar
> BetterAdvancements-1.19.2-0.2.2.142.jar
> betteranimalsplus-1.19-11.0.7-forge.jar
> BetterAnimationsCollection-v4.0.5-1.19.2-Forge.jar
> BetterF3-1.3.2-Fabric-1.19.jar
> bettervillage-forge-1.19.2-2.0.0.jar
> biomemakeover-FORGE-1.19.2-1.5.12.jar
> BiomesOPlenty-1.19.2-17.1.1.150.jar
> blueprint-1.19.2-6.1.0.jar
> blue_skies-1.19.2-1.3.20.jar
> Bookshelf-Forge-1.19.2-16.1.11.jar
> BotanyPots-Forge-1.19.2-9.0.13.jar
> BotanyTrees-Forge-1.19.2-5.0.2.jar
> broglisbugs-0.1.3-1.19.jar
> BroomsMod-1.19-1.1.1.jar
> carryon-1.19-1.18.1.2.jar
> catalogue-1.6.3-1.19.jar
> charmofundying-forge-6.0.0+1.19.2.jar
> Chimes-1.1.4-1.19.jar
> citadel-2.0.0-1.19.jar
> comforts-forge-6.0.1+1.19.2.jar
> Companion-1.19.1-forge-3.0.2.jar
> Compat-O-Plenty-1.19.2-2.0.1.jar
> connectedglass-1.1.4b-forge-mc1.19.jar
> Controlling-forge-1.19.2-10.0+7.jar
> corpse-1.19.2-1.0.0.jar
> Croptopia-1.19.2-FORGE-2.1.0.jar
> curios-forge-1.19.2-5.1.1.0.jar
> customizableelytra-1.19.0-1.7.2.jar
> DeathKnell-Forge-1.19.2-6.0.3.jar
> Decorative+Blocks-forge-1.19.2-3.0.0.jar
> DiagonalFences-v4.2.3-1.19.2-Forge.jar
> dynamiclights-1.19.2.1.jar
> dynview-1.19.1-2.9.jar
> EarthMobs-1.19.2-3.2.1.jar
> ecologics-forge-1.19.2-2.1.10.jar
> exlinefurniture-forge-1.19-v2.1.2.jar
> extragolems-19.2.4.jar
> FastLeafDecay-30.jar
> flowerseeds-1.19.2-4.0.1.jar
> furniture-6.3.2-1.12.2.jar
> geckolib-forge-1.19-3.1.21.jar
> immersive_armors-1.4.2.jar
> Jade-1.19.1-forge-8.3.0.jar
> jei-1.19.2-forge-11.3.0.262.jar
> JustEnoughResources-1.18.2-0.14.1.171.jar
> kotlinforforge-3.7.1-obf.jar
> lava-java-0.4.1.jar
> letmedespawn-1.18.x-1.19.x-forge-1.0.3.jar
> libraryferret-forge-1.19.2-3.0.0.jar
> mcw-doors-1.0.7-mc1.19.2.jar
> mcw-lights-1.0.4-mc1.19.2.jar
> mcw-paintings-1.0.4-mc1.19.2.jar
> mcw-windows-2.0.3-mc1.19.jar
> metalbarrels-1.19.2-5.0.1.jar
> modlist.txt
> modmenu-4.0.6.jar
> modnametooltip-1.19-1.19.0.jar
> moonlight-1.19.2-2.0.30.jar
> moonlight-1.19.2-2.1.13-forge.jar
> More+Babies-forge-1.19.1-1.0.0.jar
> morefrogs-1.19.x-1.1.1-forge.jar
> MouseTweaks-forge-mc1.19-2.23.jar
> mvs-3.1.3.jar
> mythicmounts-1.19-7.0.jar
> naturalist-forge-2.1.1-1.19.2.jar
> NaturesCompass-1.19.2-1.9.7-forge.jar
> Netherrocks-1.19.2-5.1.0.2.jar
> Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.11.jar
> Patchouli-1.19.2-77.jar
> player_companions_1.19.2-4.2.0.jar
> pluto-mc1.19.2-0.0.1.jar
> polymorph-forge-0.45.0+1.19.2.jar
> productivebees-1.19.2-0.10.3.1.jar
> PuzzlesLib-v4.3.12-1.19.2-Forge.jar
> Quark-3.3-371.jar
> QuarkOddities-1.18.jar
> radon-0.8.2.jar
> Red+Panda-1.19.2-1.0.0.jar
> repurposed_structures_forge-6.3.0+1.19.2.jar
> rubidium-0.6.2.jar
> SelectablePainting-1.19.2-2.0.2.jar
> Shrines-1.19.2-5.0.0-alpha4.jar
> SimpleCoreLib-1.19.2-5.1.0.2.jar
> simplehats-forge-1.19.2-0.1.5.jar
> SimpleStorageNetwork-1.19-1.6.4.jar
> smallships-1.19.2-2.0.0-Alpha-0.4.jar
> smoothchunk-1.19.1-2.0.jar
> spark-1.9.40-forge.jar
> Structory-1.19-1.2.jar
> structure_gel-1.19.2-2.6.2.jar
> sullysmod-2.1.0-beta.jar
> supermartijn642corelib-1.0.19a-forge-mc1.19.jar
> supplementaries-1.19.2-2.2.26.jar
> swingthroughgrass-1.19-1.10.0.jar
> TerraBlender-forge-1.19.2-2.0.1.127.jar
> Tips-Forge-1.19.2-8.0.25.jar
> toofast-1.19-1.0.0.jar
> torchmaster-19.2.0.jar
> trashcans-1.0.15b-forge-mc1.19.jar
> TravelersBackpack-1.19.2-8.2.9.jar
> twilightforest-1.19-4.2.1421-universal.jar
> veinmining-forge-1.0.0-beta.2+1.19.2.jar
> VisualWorkbench-v4.2.0-1.19.2-Forge.jar
> waystones-forge-1.19-11.1.0.jar
> XaerosWorldMap_1.28.4_Forge_1.19.1.jar
> Xaeros_Minimap_22.16.3_Forge_1.19.1.jar
> xptome-1.19-2.1.6.jar
>

**Comment by AbdElAziz333** [comment]
You are using 1.19.2-0.0.3 versin which is OUT-DATED, Try the latest version of [Canary](https://www.curseforge.com/minecraft/mc-mods/canary/files/4094216).

**Comment by TathanDev** [comment]
I use the latest version

**Comment by AbdElAziz333** [comment]
i will look into that.

**Comment by Filipsi** [comment]
I have encountered the same problem after updating server to Forge 43.2.0
[crash-2022-12-11_21.56.45-server.txt](https://github.com/AbdElAziz333/Canary/files/10204971/crash-2022-12-11_21.56.45-server.txt)

**Comment by AbdElAziz333** [comment]
should be fixed in the new updates.
[1.19.3](https://www.curseforge.com/minecraft/mc-mods/canary/files/4291690) - [1.19.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4291688) - [1.18.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4291687) .
Good luck!

**Comment by xam290** [comment]
Problem still exists in "**canary-mc1.20.1-0.2.10.jar**"

**Comment by AbdElAziz333** [comment]
@xam290 Please open a new issue with a log or crash report.
