### ISSUE TITLE
Canary crashing clients at Getting Biome

### ISSUE THREAD

**Issue by xxShihiro** [AbdElAziz333/Canary#68]
Version: Canary 1.18.2 0.0.10
> 
How to recreate: Join server with canary installed server-side only.

CRASHFILE/CRASHLOG:
[crash-2022-12-19_00.38.46-client.txt](https://github.com/AbdElAziz333/Canary/files/10254293/crash-2022-12-19_00.38.46-client.txt)
 Report File

I have canary installed server-side along almost all of the CaffeineMC optimization mods ported to forge. I'm seeing sodium and xaero's minimap in the logs so I'm wondering if it has something to do with "Rubidium (Sodium forge fork)"

**Comment by AbdElAziz333** [comment]
can you try with only Canary?

**Comment by TorchyBoi** [comment]
[crash-2022-12-28_20.11.30-client.txt](https://github.com/AbdElAziz333/Canary/files/10325760/crash-2022-12-28_20.11.30-client.txt)
[crash-2022-12-28_20.12.34-client.txt](https://github.com/AbdElAziz333/Canary/files/10325761/crash-2022-12-28_20.12.34-client.txt)
[crash-2022-12-28_20.30.42-client.txt](https://github.com/AbdElAziz333/Canary/files/10325762/crash-2022-12-28_20.30.42-client.txt)
[crash-2022-12-30_17.50.19-client.txt](https://github.com/AbdElAziz333/Canary/files/10325763/crash-2022-12-30_17.50.19-client.txt)

I'm running the same one (tried with different versions of Canary) though this one is for Minecraft 1.19.2 (canary-mc1.19.2-0.1.4.jar)

**Comment by AbdElAziz333** [comment]
should be fixed in the new updates.
[1.19.3](https://www.curseforge.com/minecraft/mc-mods/canary/files/4291690) - [1.19.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4291688) - [1.18.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4291687) .
Good luck!
