### ISSUE TITLE
Canary crash with "Eureka! Airships!"

### ISSUE THREAD

**Issue by MrJasonRus** [AbdElAziz333/Canary#69]
Version: Canary 1.18.2 0.0.10

Modlist:
![image](https://user-images.githubusercontent.com/31430536/208341694-5bd71b18-a4bc-4974-9710-110b49920e96.png)

Crash-report:
[crash-2022-12-19_08.16.54-fml.txt](https://github.com/AbdElAziz333/Canary/files/10255683/crash-2022-12-19_08.16.54-fml.txt)

**Comment by AbdElAziz333** [comment]
i will look into that.
