### ISSUE TITLE
Dangerous Stonecutter Crash

### ISSUE THREAD

**Issue by LaidBackSloth** [AbdElAziz333/Canary#7]
### Version

Example: canary-mc1.18.2-0.0.3

### Reproduction Steps

Start Minecraft with Canary and Dangerous Stonecutter

### Crash Report File

[crash-2022-09-12_18.12.11-client.txt](https://github.com/AbdElAziz333/Canary/files/9549836/crash-2022-09-12_18.12.11-client.txt)

### Additional Information

Downgrading to version 0.0.1 fixes it

**Comment by AbdElAziz333** [comment]
Fixed in 0.0.4 version
