### ISSUE TITLE
Client crashes when connecting to 1.18.2 server

### ISSUE THREAD

**Issue by RealEmanGaming** [AbdElAziz333/Canary#70]
### Version

> canary-mc1.18.2-0.0.10

### Reproduction Steps

> 1. Place canary-mc1.18.2-0.0.10.jar in server's "mods" folder
> 2. Join said server

### Crash Report File

> [Client Crash Log](https://gist.github.com/RealEmanGaming/af2823a53cfcf7f60c00564e680d61fa)
> [Server Debug Log](https://gist.github.com/RealEmanGaming/af2823a53cfcf7f60c00564e680d61fa)

### Minecraft Save

> N/A

### Additional Information

> Client has no mods installed
> Server has no additional mods
> Both client and server are running the latest version of Forge as of writing (40.1.92)

**Comment by AbdElAziz333** [comment]
Can you try without Canary? if you connected to the server, could you try to use Canary 0.1.0 ?

**Comment by ProfessorFartsalot** [comment]
> Can you try without Canary? if you connected to the server, could you try to use Canary 0.1.0 ?

I have the same problem, can confirm canary is causing it. 0.1.0 didn't appear to fix my problem either.

**Comment by ProfessorFartsalot** [comment]
[crash-2022-12-31_01.12.03-client.txt](https://github.com/AbdElAziz333/Canary/files/10326896/crash-2022-12-31_01.12.03-client.txt)

**Comment by AbdElAziz333** [comment]
should be fixed in the new updates.
[1.19.3](https://www.curseforge.com/minecraft/mc-mods/canary/files/4291690) - [1.19.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4291688) - [1.18.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4291687) .
Good luck!
