### ISSUE TITLE
Villager can't find a job site [1.19.2]

### ISSUE THREAD

**Issue by KTheRD** [AbdElAziz333/Canary#71]
### Version Information

canary-mc1.19.2-0.1.3

### Expected Behavior

Villagers can find a job site block on any Y coordinate.

### Actual Behavior

Villager can't find a job site block if it is on 192 Y coordinate or higher.

### Reproduction Steps

1. Build a platform at 191 Y coordinate
2. Place a composter on it, so it will be at 192 Y coordinate
3. Spawn a villager
4. Observe that villager can't get a job

### Other Information

mixin.ai.poi=false fixes the bug.

**Comment by CodeIsNotEvil** [comment]
### Version Information
canary-mc1.19.2-0.1.6
### After some testing 
It looks like the mod prevents the registration of any villager poi generated or placed.

**Comment by ShamHyper** [comment]
There was the same problem on this version, I confirm

**Comment by AbdElAziz333** [comment]
can you please try the new update?
