### ISSUE TITLE
PRIVATE @Overwrite method m_22543_ in canary.mixins.json:ai.task.memory_change_counting.BehaviorMixin causes a crash

### ISSUE THREAD

**Issue by utterlynowhere** [AbdElAziz333/Canary#73]
### Version

canary-mc1.18.2-0.0.10

### Reproduction Steps

1. Install Canary
2. Install Occultism alongside its required Dependencies
3. Launch game
4. Crash

### Crash Report File

[latest.log](https://github.com/AbdElAziz333/Canary/files/10298292/latest.log)

### Additional Information

No other mods are installed except for the mods mentioned above.

**Comment by AbdElAziz333** [comment]
Can you use this [version](https://www.curseforge.com/minecraft/mc-mods/canary/files/4260286)?

**Comment by utterlynowhere** [comment]
Apologies for the the late testing. Works now! Thank you very much.
