### ISSUE TITLE
Canary dedicated server crash on "lightly" modded pack (no client crash)

### ISSUE THREAD

**Issue by 400Ferrets** [AbdElAziz333/Canary#77]
[crash-2022-12-30_10.34.14-server.txt](https://github.com/AbdElAziz333/Canary/files/10326598/crash-2022-12-30_10.34.14-server.txt)
Server will crash when a gantry from the create mod is built and moved. Crash is very consistent, and cannot be reproduced in a single player world on the client. Tested on java 17 and 19, with no difference. Crash does not occur with canary removed.

I also tested with just Canary and Create and observed the same crash. 
[crash-2022-12-31_00.49.18-server.txt](https://github.com/AbdElAziz333/Canary/files/10326630/crash-2022-12-31_00.49.18-server.txt)

**Comment by Nouwan** [comment]
We have this issue as well. If it is useful I can provide logs.

**Comment by Nouwan** [comment]
After some debugging I found a workaround setting mixin.chunk.entity_class_groups = false resolved the issue for me.

**Comment by AbdElAziz333** [comment]
should be fixed in the new updates.
[1.19.3](https://www.curseforge.com/minecraft/mc-mods/canary/files/4291690) - [1.19.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4291688) - [1.18.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4291687) .
Good luck!

**Comment by Nouwan** [comment]
Thanks amazing quick response any way I can help support the project?

**Comment by Thecrafteur111** [comment]
Hello, I had a similar crash with the last versions of Create and Canary. Removing Canary solved the issue.

[crash-2023-03-14_19.35.50-server.txt](https://github.com/AbdElAziz333/Canary/files/10973174/crash-2023-03-14_19.35.50-server.txt)

**Comment by JakeSteinebronn** [comment]
+1, it appears as if this bug has resurfaced with the lastest Canary 0.1.10 for 1.19.2
