### ISSUE TITLE
Crash when using Ponder feature from Create. (Used on the Deployer Item)

### ISSUE THREAD

**Issue by alexhowell610** [AbdElAziz333/Canary#8]
------------------------

Version: Canary 1.18.2-0.0.3 
1.) Use the Ponder feature from Create for the Deployer item
2.) Wait ~10 seconds
3.) Game Crashes

Tested multiple times on multiple worlds, same result.
### Crash Report File

[crash-2022-09-12_12.13.34-client.txt](https://github.com/AbdElAziz333/Canary/files/9550756/crash-2022-09-12_12.13.34-client.txt)

I disabled Canary and used Ponder on the exact same item and did not get a crash

**Comment by Phweeeee** [comment]
Can confirm.

**Comment by Cykes95** [comment]
I get the crash using the pounder too but at random moments. Im my case i get an error involving Canary and Create

[crash-2022-09-27_02.35.17-client-.txt](https://github.com/AbdElAziz333/Canary/files/9650516/crash-2022-09-27_02.35.17-client-.txt)

**Comment by WinZZer** [comment]
This issue can be fixed by adding mixin.entity.collisions=false in canary.properties at config folder.
Ponder feature will work without crash.

**Comment by AbdElAziz333** [comment]
fixed in 1.18.2-0.0.6 version and the same fix will be added to 1.19.2.
