### ISSUE TITLE
Server 1.19.2 Forge 43.2.3 - Crashes when on Client, Resets all chunk when on server

### ISSUE THREAD

**Issue by michael554466** [AbdElAziz333/Canary#81]
### Version Information

>canary-mc1.19.2-0.1.5.jar

### Expected Behavior

>Load the world normaly and help optimize Clients and the Server

### Actual Behavior

>Chunks where all reset upon opening the world.

### Reproduction Steps

>1. Install forge 1.19.2 Forge 43.2.3 on a Client & Add canary-mc1.19.2-0.1.5.jar to the mods folder

>2. Install forge 1.19.2 Forge 43.2.3 on a Server

>3. Try to log into the Server with the Client

>4. There will be an error: Internal Exception: java.lang.IllegalArgumentException: Registry ResourceKey[minecraft:root / apoli:configured_power] was missing

>5. Add canary-mc1.19.2-0.1.5.jar to the Server mods folder

>6. Try to join again, it will load, but will reset all chunks - undoing all changes made by the players.

>7. This persists after uploading backups for the world.

### Other Information

>Server & Client: 1.19.2 Forge 43.2.3
![image](https://user-images.githubusercontent.com/5871142/210502028-533fdd35-4086-428a-9101-9edf42919442.png)

(I have footage of the whole incident, avalible apon request)

**Comment by zalfrost** [comment]
There is a new version available. Try that new one (canary-mc1.19.3-0.1.6.jar) on curseforged.

**Comment by AbdElAziz333** [comment]
Yes, this issue if fixed in the new 0.1.6 version for MC 1.19.3 & 1.19.2 and 0.1.2 for MC 1.18.2.
