### ISSUE TITLE
1.19.2 Error with Canary update

### ISSUE THREAD

**Issue by Zelioth** [AbdElAziz333/Canary#82]
### Read me before you open an issue! ###

------------------------

### Version Information

canary - mc 1.19.2 - 0.1.5

Seems to be some sort of crash while exploring a new world. Mimics the last issue that was reported. doesn't happen right away and I only tested single player and the crash happened. 

[crash-2023-01-04_20.12.01-server.tx
[latest.log](https://github.com/AbdElAziz333/Canary/files/10348918/latest.log)
t](https://github.com/AbdElAziz333/Canary/files/10348917/crash-2023-01-04_20.12.01-server.txt)

**Comment by AbdElAziz333** [comment]
This is old Canary version and this issue is fixed by the new [update](https://www.curseforge.com/minecraft/mc-mods/canary/files/4296173).

**Comment by Zelioth** [comment]
I apologize but this issue is not the old version. I am running Canary 0.1.6 as indicated in the log and crash report posted. I just mistyped. This crash happened on 1.19.3 version of MC with thte LATEST version of canary installed
