### ISSUE TITLE
Nether Portal linking issue

### ISSUE THREAD

**Issue by Tander** [AbdElAziz333/Canary#85]
### Version Information

canary-mc1.19.2-0.1.6

### Expected Behavior

Portals link correctly

### Actual Behavior

Moving though portal cause new one to open, instead of using existing one.
mixin.ai.poi.fast_portals=false helps to fix it in one direction (overworld -> nether), but only mixin.ai.poi=false fixes issue completely.
Looks similar to https://github.com/CaffeineMC/lithium-fabric/issues/374 and https://github.com/CaffeineMC/lithium-fabric/issues/375 (fixed in lithium 0.8.1: https://www.curseforge.com/minecraft/mc-mods/lithium/files/3865696)

### Reproduction Steps

1. Create a pair of portals, for example
![изображение](https://user-images.githubusercontent.com/1059805/210925737-f6e3bfe4-e355-4507-a2b5-f752674ab1c9.png)

2. Try to use it

3. 
![изображение](https://user-images.githubusercontent.com/1059805/210925811-ce91419a-7c3e-43f2-8164-044d5fc7f8ae.png)

**Comment by NideVice** [comment]
same problem

**Comment by AbdElAziz333** [comment]
could you please test the new version?
[1.19.3](https://www.curseforge.com/minecraft/mc-mods/canary/files/4307894) - [1.19.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4307893) - [1.18.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4307891).

**Comment by NideVice** [comment]
> could you please test the new version? [1.19.3](https://www.curseforge.com/minecraft/mc-mods/canary/files/4307894) - [1.19.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4307893) - [1.18.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4307891).

no change in the situation

**Comment by NideVice** [comment]
> could you please test the new version? [1.19.3](https://www.curseforge.com/minecraft/mc-mods/canary/files/4307894) - [1.19.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4307893) - [1.18.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4307891).

personally, it worked fine
