### ISSUE TITLE
bees have forgotten how to enter the hives and nests

### ISSUE THREAD

**Issue by NideVice** [AbdElAziz333/Canary#86]
### Version Information
> canary-mc1.19.2-0.1.6

### Expected Behavior
> Bees will pollinate flowers and fly into the hives or/and nests

### Actual Behavior
> Bees just fly around without getting attached to the hive or nest

### Reproduction Steps
>This bug easy to reproduce if you remove canary from the modpack.
> 1. If the nest is generated, then collect honey from it and bees will not fly into it anymore.
> 2. If you place a beehive, the bees simply ignore it, and fly away to Hawaii

### Other Information
> -

**Comment by AbdElAziz333** [comment]
could you please test the new version?
[1.19.3](https://www.curseforge.com/minecraft/mc-mods/canary/files/4307894) - [1.19.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4307893) - [1.18.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4307891).

**Comment by NideVice** [comment]
> could you please test the new version? [1.19.3](https://www.curseforge.com/minecraft/mc-mods/canary/files/4307894) - [1.19.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4307893) - [1.18.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4307891).

bees have stopped pollinating flowers and still ignore hives

**Comment by NideVice** [comment]
> could you please test the new version? [1.19.3](https://www.curseforge.com/minecraft/mc-mods/canary/files/4307894) - [1.19.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4307893) - [1.18.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4307891).

thanks everything worked
