### ISSUE TITLE
Composters and Hoppers are no longer compatable.

### ISSUE THREAD

**Issue by BeckPhillips** [AbdElAziz333/Canary#87]
### Version Information

[Canary 0.1.7 for MC 1.19.3](https://www.curseforge.com/minecraft/mc-mods/canary/files/4307894)

### Expected Behavior

> Composters should be fillable with Hoppers
>
> Example: When a hopper is filled with seeds, it should compost them.

### Actual Behavior

> Composters and hoppers do not interact.
>
> Example: No interaction.

### Reproduction Steps
> 1. Place a hopper on top of a composter
> 2. Add seeds to the hopper
> 3. Nothing happens

### Other Information

> Link to the server's modpack can be found [here](https://www.curseforge.com/minecraft/modpacks/nice-mop)
> Canary was removed due to this issue, as well as a few other minor problems
> 
> There are a few other bug reports for this, but they don't seem to have all of the information.

**Comment by Dr4g00n92** [comment]
Can confirm, same for me. 
Setting mixin.alloc.composter=false in the config did not fix it.
Removed the mod and it worked again.

**Comment by AbdElAziz333** [comment]
This issue should be fixed in the newer versions.
[1.18.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4324082) - [1.19.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4324084) - [1.19.3](https://www.curseforge.com/minecraft/mc-mods/canary/files/4324087)

I hope you have a good day!

**Comment by der10pm** [comment]
This bug seems to have reappeared. At least in canary 1.19.2-0.2.4 I have this excact problem.
