### ISSUE TITLE
Please Label the Resetting World Bug Fix as Release and not Beta

### ISSUE THREAD

**Issue by Lucipo** [AbdElAziz333/Canary#88]
Curseforge Launcher does not automatically update mods to versions labelled "beta", so I updated my mods and lost my entire world today. Not really even the developer's of this mods fault (tbf how do you miss this in testing the new version) but its curseforge consistently being the biggest middle finger to the modded mc community consistently. Also I shouldve gotten a backup mod and have one now but bruh....

Please label the 0.1.6 and 0.1.7 versions as Release to prevent more people's worlds from being wiped.

**Comment by BeckPhillips** [comment]
My entire server literally just got deleted, I'm ready to riot because we're about to fight the ender dragon in like 30 minutes.

**Comment by AbdElAziz333** [comment]
I'am so sorry for that!

**Comment by BeckPhillips** [comment]
Are you saying that you _don't_ test your updates before releasing them?

**Comment by VuFlub** [comment]
I lost my entire world...

**Comment by AbdElAziz333** [comment]
No, i tested it but in a new world so no chunks is got removed, i will tested any new version in a existing world, and i'am so sorry for you all.

**Comment by AbdElAziz333** [comment]
This issue will pinned on, if you updated Canary to the latest update and you lost your world please make an issue and update to the latest version, your world will back again after reporting, but also don't worry anymore this issue will never happen again.
