### ISSUE TITLE
1.16 port?

### ISSUE THREAD

**Issue by No1129** [AbdElAziz333/Canary#9]
You may say "just use roadrunner"
roadrunner was last updated in march
and the updated was one fix
so roadrunner is in limbo
and a forge port of lithium thats on 1.16 thats get updated more often would be nice

**Comment by AbdElAziz333** [comment]
1.16.5 is OUTDATED, and i never planned for that, and Canary focuses in the modern versions of Minecraft which is 1.18, 1.19, 1.20, + etc.
