### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by xSLUMA** [AbdElAziz333/Canary#95]
On my 1.19.2 Forge server using the latest build for that version after a while of running the server eventually the RAM usage climbs up to max essentially killing the server, this can be either really quick or take over 30 minutes. After running a spark profiler we think that over 4GB of our 8GB of RAM was being used by canary and I have tried removing the mod and the server has stopped leaking memory we think however the benefits of the mod take a hit.

This is the link to the spark profiler I believe: https://spark.lucko.me/kTwvWtxago

canary-mc1.19.2-0.1.8

**Comment by AbdElAziz333** [comment]
can you try the newer versions? if not could you provide a new spark profiler report?
